import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    'navigation.dashboard': 'Dashboard',
    'navigation.calendar': 'Calendário',
    'navigation.schedule': 'Cronograma',
    'navigation.revision': 'Revisão',
    'navigation.flashcards': 'Flashcards',
    'navigation.settings': 'Configurações',
    'navigation.profile': 'Perfil',
    
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Tarefas de Hoje',
    'dashboard.noRevisionsToday': 'Nenhuma revisão para hoje! 🎉',
    'dashboard.start': 'Iniciar',
    'dashboard.complete': 'Concluir',
    'dashboard.postpone': 'Adiar',
    'dashboard.dailyProgress': 'Progresso Diário',
    'dashboard.tasks': 'tarefas',
    'dashboard.weeklyProgress': 'Progresso Semanal',
    'dashboard.upcomingRevisions': 'Próximas Revisões',
    'dashboard.overdue': 'Atrasadas',
    'dashboard.today': 'Hoje',
    'dashboard.thisWeek': 'Esta Semana',
    'dashboard.overview': 'Visão Geral',
    'dashboard.studyStats': 'Estatísticas de Estudo',
    'dashboard.recentActivity': 'Atividade Recente',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.createRevision': 'Criar Revisão',
    'dashboard.createFlashcard': 'Criar Flashcard',
    'dashboard.scheduleEvent': 'Agendar Evento',
    
    'schedule.title': 'Cronograma',
    'schedule.subtitle': 'Gerencie sua agenda e eventos',
    'schedule.newEvent': 'Novo Evento',
    'schedule.createEvent': 'Criar Evento',
    'schedule.editEvent': 'Editar Evento',
    'schedule.deleteEvent': 'Excluir Evento',
    'schedule.eventTitle': 'Título do Evento',
    'schedule.eventDescription': 'Descrição do Evento',
    'schedule.eventDate': 'Data do Evento',
    'schedule.eventTime': 'Horário do Evento',
    'schedule.eventType': 'Tipo do Evento',
    'schedule.eventLocation': 'Local do Evento',
    'schedule.saveEvent': 'Salvar Evento',
    'schedule.cancelEvent': 'Cancelar',
    'schedule.todayEvents': 'Eventos de Hoje',
    'schedule.noEventsToday': 'Nenhum evento para hoje',
    'schedule.upcomingEvents': 'Próximos Eventos',
    'schedule.noUpcomingEvents': 'Nenhum evento próximo',
    'schedule.allEvents': 'Todos os Eventos',
    'schedule.thisWeek': 'Esta Semana',
    'schedule.nextWeek': 'Próxima Semana',
    'schedule.calendar': 'Calendário',
    'schedule.agenda': 'Agenda',
    'schedule.eventCreated': 'Evento criado com sucesso',
    'schedule.eventUpdated': 'Evento atualizado com sucesso',
    'schedule.eventDeleted': 'Evento excluído com sucesso',
    'schedule.confirmDelete': 'Tem certeza que deseja excluir este evento?',
    'schedule.noEvents': 'Nenhum evento encontrado',
    'schedule.addEvent': 'Adicionar Evento',
    'schedule.viewEvent': 'Ver Evento',
    'schedule.eventDetails': 'Detalhes do Evento',
    'schedule.repeatEvent': 'Repetir Evento',
    'schedule.reminderTime': 'Lembrete',
    'schedule.priority': 'Prioridade',
    'schedule.high': 'Alta',
    'schedule.medium': 'Média',
    'schedule.low': 'Baixa',
    'schedule.today': 'Hoje',
    'schedule.day': 'Dia',
    'schedule.week': 'Semana',
    'schedule.month': 'Mês',
    
    'revision.title': 'Sistema de Revisão',
    'revision.subtitle': 'Gerencie seus materiais de estudo com repetição espaçada',
    'revision.createRevision': 'Criar Revisão',
    'revision.createNew': 'Criar Nova',
    'revision.myRevisions': 'Minhas Revisões',
    'revision.pending': 'Pendentes',
    'revision.priority': 'Prioridade',
    'revision.completed': 'Concluídas',
    'revision.all': 'Todas',
    'revision.noRevisions': 'Nenhuma revisão encontrada',
    'revision.searchPlaceholder': 'Buscar revisões...',
    'revision.dueToday': 'Vence Hoje',
    'revision.overdue': 'Atrasadas',
    'revision.upcoming': 'Próximas',
    'revision.statistics': 'Estatísticas',
    'revision.totalRevisions': 'Total de Revisões',
    'revision.completedToday': 'Concluídas Hoje',
    'revision.pendingReview': 'Pendentes de Revisão',
    'revision.forToday': 'Para Hoje',
    'revision.revisionsFor': 'Revisões para',
    'revision.noRevisionsToday': 'Nenhuma revisão para hoje! 🎉',
    'revision.noUpcomingRevisions': 'Nenhuma revisão próxima',
    'revision.noCompletedRevisions': 'Nenhuma revisão concluída',
    'revision.viewContent': 'Ver Conteúdo',
    'revision.complete': 'Concluir',
    'revision.postpone': 'Adiar',
    'revision.delete': 'Excluir',
    'revision.title.placeholder': 'Título da revisão',
    'revision.content.placeholder': 'Conteúdo da revisão',
    'revision.tags.placeholder': 'Tags (separadas por vírgula)',
    'revision.difficulty': 'Dificuldade',
    'revision.easy': 'Fácil',
    'revision.medium': 'Médio',
    'revision.hard': 'Difícil',
    'revision.created': 'Revisão criada com sucesso',
    'revision.updated': 'Revisão atualizada com sucesso',
    'revision.deleted': 'Revisão excluída com sucesso',
    'revision.confirmDelete': 'Tem certeza que deseja excluir esta revisão?',
    'revision.editRevision': 'Editar Revisão',
    'revision.saveRevision': 'Salvar Revisão',
    'revision.cancelRevision': 'Cancelar',
    
    'flashcards.title': 'Flashcards',
    'flashcards.subtitle': 'Sistema de estudos com flashcards inteligentes',
    'flashcards.loading': 'Carregando...',
    'flashcards.createDeck': 'Criar Deck',
    'flashcards.importDeck': 'Importar Deck',
    'flashcards.totalDecks': 'Total de Decks',
    'flashcards.totalCards': 'Total de Cards',
    'flashcards.toReview': 'Para Revisar',
    'flashcards.searchDecks': 'Buscar decks...',
    'flashcards.myDecks': 'Meus Decks',
    'flashcards.noDecksFound': 'Nenhum deck encontrado',
    'flashcards.noDecksCreate': 'Nenhum deck criado ainda. Crie seu primeiro deck!',
    'flashcards.cards': 'cards',
    'flashcards.toReviewShort': 'revisar',
    'flashcards.confirmDelete': 'Tem certeza que deseja deletar este deck?',
    'flashcards.statistics': 'Estatísticas',
    'flashcards.studyProgress': 'Progresso de Estudo',
    'flashcards.performance': 'Desempenho',
    'flashcards.deckName': 'Nome do Deck',
    'flashcards.deckDescription': 'Descrição do Deck',
    'flashcards.createCard': 'Criar Card',
    'flashcards.editCard': 'Editar Card',
    'flashcards.front': 'Frente',
    'flashcards.back': 'Verso',
    'flashcards.addCard': 'Adicionar Card',
    'flashcards.saveCard': 'Salvar Card',
    'flashcards.deleteCard': 'Excluir Card',
    'flashcards.studyDeck': 'Estudar Deck',
    'flashcards.showAnswer': 'Mostrar Resposta',
    'flashcards.again': 'Novamente',
    'flashcards.good': 'Bom',
    'flashcards.easy': 'Fácil',
    'flashcards.studyComplete': 'Estudo Completo!',
    'flashcards.noCardsToReview': 'Nenhum card para revisar',
    'flashcards.deckCreated': 'Deck criado com sucesso',
    'flashcards.deckUpdated': 'Deck atualizado com sucesso',
    'flashcards.deckDeleted': 'Deck excluído com sucesso',
    'flashcards.cardCreated': 'Card criado com sucesso',
    'flashcards.cardUpdated': 'Card atualizado com sucesso',
    'flashcards.cardDeleted': 'Card excluído com sucesso',
    
    'settings.title': 'Configurações',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Selecione um idioma',
    'settings.portuguese': 'Português',
    'settings.english': 'Inglês',
    'settings.spanish': 'Espanhol',
    'settings.notifications': 'Notificações',
    'settings.notifications.desc': 'Configure suas preferências de notificação',
    'settings.emailNotifications': 'Notificações por email',
    'settings.pushNotifications': 'Notificações push',
    'settings.pushNotifications.desc': 'Receba notificações no seu dispositivo',
    'settings.saveChanges': 'Salvar alterações',
    'settings.changesSaved': 'Alterações salvas com sucesso!',
    'settings.changesSaved.desc': 'Suas configurações foram atualizadas',
    'settings.study': 'Estudos',
    'settings.study.reminders': 'Lembretes de Estudo',
    'settings.study.reminders.desc': 'Receba lembretes para suas sessões de estudo',
    'settings.study.autoBackup': 'Backup Automático',
    'settings.study.autoBackup.desc': 'Faça backup automático dos seus dados',
    'settings.appearance': 'Aparência',
    'settings.appearance.desc': 'Personalize a aparência do aplicativo',
    'settings.appearance.theme': 'Tema',
    'settings.appearance.darkMode': 'Modo Escuro',
    'settings.appearance.lightMode': 'Modo Claro',
    'settings.appearance.systemMode': 'Seguir Sistema',
    'settings.darkMode': 'Modo Escuro',
    'settings.darkMode.desc': 'Alterne entre o modo claro e escuro',
    'settings.studyReminders': 'Lembretes de Estudo',
    'settings.studyReminders.desc': 'Receba lembretes para suas sessões de estudo',
    'settings.pomodoro': 'Pomodoro',
    'settings.pomodoro.desc': 'Configure suas sessões de foco',
    'settings.focusTime': 'Tempo de Foco (min)',
    'settings.shortBreak': 'Pausa Curta (min)',
    'settings.longBreak': 'Pausa Longa (min)',
    'settings.longBreakInterval': 'Intervalo Pausa Longa',
    'settings.autoStartBreaks': 'Iniciar Pausas Automaticamente',
    'settings.autoStartBreaks.desc': 'Inicie as pausas automaticamente após o foco',
    'settings.resetData': 'Redefinir Dados',
    'settings.resetData.desc': 'Redefina ou limpe seus dados',
    'settings.deleteSchedule': 'Excluir Cronograma',
    'settings.deleteSchedule.btn': 'Excluir Cronograma',
    'settings.deleteAllData': 'Excluir Todos os Dados',
    'settings.deleteAllData.btn': 'Excluir Todos os Dados',
    'settings.scheduleDeleted': 'Cronograma excluído',
    'settings.scheduleDeleted.desc': 'Todos os eventos foram removidos',
    'settings.allDataDeleted': 'Todos os dados excluídos',
    'settings.allDataDeleted.desc': 'Todos os dados foram removidos',
    'settings.general': 'Geral',
    'settings.account': 'Conta',
    'settings.privacy': 'Privacidade',
    'settings.about': 'Sobre',
    
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.personalInfo.desc': 'Gerencie suas informações pessoais e de contato',
    'profile.name': 'Nome',
    'profile.firstName': 'Primeiro Nome',
    'profile.lastName': 'Sobrenome',
    'profile.firstName.placeholder': 'Digite seu primeiro nome',
    'profile.lastName.placeholder': 'Digite seu sobrenome',
    'profile.email': 'E-mail',
    'profile.email.placeholder': 'Digite seu e-mail',
    'profile.phone': 'Telefone',
    'profile.phone.placeholder': 'Digite seu telefone',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Conte um pouco sobre você',
    'profile.preferences': 'Preferências',
    'profile.theme': 'Tema',
    'profile.light': 'Claro',
    'profile.dark': 'Escuro',
    'profile.system': 'Sistema',
    'profile.saveChanges': 'Salvar alterações',
    'profile.changesSaved': 'Alterações salvas com sucesso!',
    'profile.changePassword': 'Alterar Senha',
    'profile.currentPassword': 'Senha Atual',
    'profile.newPassword': 'Nova Senha',
    'profile.confirmPassword': 'Confirmar Nova Senha',
    'profile.currentPassword.placeholder': 'Digite sua senha atual',
    'profile.newPassword.placeholder': 'Digite sua nova senha',
    'profile.confirmPassword.placeholder': 'Confirme sua nova senha',
    'profile.passwordChanged': 'Senha alterada com sucesso',
    'profile.profileUpdated': 'Perfil atualizado com sucesso',
    'profile.uploadPhoto': 'Alterar foto de perfil',
    'profile.removePhoto': 'Remover foto',
    'profile.photoUpdated': 'Foto atualizada com sucesso',
    
    // Botões e ações comuns
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Visualizar',
    'common.create': 'Criar',
    'common.update': 'Atualizar',
    'common.close': 'Fechar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.loading': 'Carregando...',
    'common.noData': 'Nenhum dado encontrado',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.confirm': 'Confirmar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.apply': 'Aplicar',
    'common.reset': 'Redefinir',
    'common.clear': 'Limpar',
    'common.select': 'Selecionar',
    'common.upload': 'Enviar',
    'common.download': 'Baixar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.refresh': 'Atualizar',
    'common.retry': 'Tentar novamente',
    'common.continue': 'Continuar',
    'common.finish': 'Finalizar',
    'common.start': 'Iniciar',
    'common.stop': 'Parar',
    'common.pause': 'Pausar',
    'common.resume': 'Retomar',
    'common.settings': 'Configurações',
    'common.help': 'Ajuda',
    'common.about': 'Sobre',
    'common.contact': 'Contato',
  },
  en: {
    'navigation.dashboard': 'Dashboard',
    'navigation.calendar': 'Calendar',
    'navigation.schedule': 'Schedule',
    'navigation.revision': 'Revision',
    'navigation.flashcards': 'Flashcards',
    'navigation.settings': 'Settings',
    'navigation.profile': 'Profile',
    
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Today\'s Tasks',
    'dashboard.noRevisionsToday': 'No revisions for today! 🎉',
    'dashboard.start': 'Start',
    'dashboard.complete': 'Complete',
    'dashboard.postpone': 'Postpone',
    'dashboard.dailyProgress': 'Daily Progress',
    'dashboard.tasks': 'tasks',
    'dashboard.weeklyProgress': 'Weekly Progress',
    'dashboard.upcomingRevisions': 'Upcoming Revisions',
    'dashboard.overdue': 'Overdue',
    'dashboard.today': 'Today',
    'dashboard.thisWeek': 'This Week',
    'dashboard.overview': 'Overview',
    'dashboard.studyStats': 'Study Statistics',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.createRevision': 'Create Revision',
    'dashboard.createFlashcard': 'Create Flashcard',
    'dashboard.scheduleEvent': 'Schedule Event',
    
    'schedule.title': 'Schedule',
    'schedule.subtitle': 'Manage your agenda and events',
    'schedule.newEvent': 'New Event',
    'schedule.createEvent': 'Create Event',
    'schedule.editEvent': 'Edit Event',
    'schedule.deleteEvent': 'Delete Event',
    'schedule.eventTitle': 'Event Title',
    'schedule.eventDescription': 'Event Description',
    'schedule.eventDate': 'Event Date',
    'schedule.eventTime': 'Event Time',
    'schedule.eventType': 'Event Type',
    'schedule.eventLocation': 'Event Location',
    'schedule.saveEvent': 'Save Event',
    'schedule.cancelEvent': 'Cancel',
    'schedule.todayEvents': 'Today\'s Events',
    'schedule.noEventsToday': 'No events for today',
    'schedule.upcomingEvents': 'Upcoming Events',
    'schedule.noUpcomingEvents': 'No upcoming events',
    'schedule.allEvents': 'All Events',
    'schedule.thisWeek': 'This Week',
    'schedule.nextWeek': 'Next Week',
    'schedule.calendar': 'Calendar',
    'schedule.agenda': 'Agenda',
    'schedule.eventCreated': 'Event created successfully',
    'schedule.eventUpdated': 'Event updated successfully',
    'schedule.eventDeleted': 'Event deleted successfully',
    'schedule.confirmDelete': 'Are you sure you want to delete this event?',
    'schedule.noEvents': 'No events found',
    'schedule.addEvent': 'Add Event',
    'schedule.viewEvent': 'View Event',
    'schedule.eventDetails': 'Event Details',
    'schedule.repeatEvent': 'Repeat Event',
    'schedule.reminderTime': 'Reminder',
    'schedule.priority': 'Priority',
    'schedule.high': 'High',
    'schedule.medium': 'Medium',
    'schedule.low': 'Low',
    'schedule.today': 'Today',
    'schedule.day': 'Day',
    'schedule.week': 'Week',
    'schedule.month': 'Month',
    
    'revision.title': 'Revision System',
    'revision.subtitle': 'Manage your study materials with spaced repetition',
    'revision.createRevision': 'Create Revision',
    'revision.createNew': 'Create New',
    'revision.myRevisions': 'My Revisions',
    'revision.pending': 'Pending',
    'revision.priority': 'Priority',
    'revision.completed': 'Completed',
    'revision.all': 'All',
    'revision.noRevisions': 'No revisions found',
    'revision.searchPlaceholder': 'Search revisions...',
    'revision.dueToday': 'Due Today',
    'revision.overdue': 'Overdue',
    'revision.upcoming': 'Upcoming',
    'revision.statistics': 'Statistics',
    'revision.totalRevisions': 'Total Revisions',
    'revision.completedToday': 'Completed Today',
    'revision.pendingReview': 'Pending Review',
    'revision.forToday': 'For Today',
    'revision.revisionsFor': 'Revisions for',
    'revision.noRevisionsToday': 'No revisions for today! 🎉',
    'revision.noUpcomingRevisions': 'No upcoming revisions',
    'revision.noCompletedRevisions': 'No completed revisions',
    'revision.viewContent': 'View Content',
    'revision.complete': 'Complete',
    'revision.postpone': 'Postpone',
    'revision.delete': 'Delete',
    'revision.title.placeholder': 'Revision title',
    'revision.content.placeholder': 'Revision content',
    'revision.tags.placeholder': 'Tags (comma separated)',
    'revision.difficulty': 'Difficulty',
    'revision.easy': 'Easy',
    'revision.medium': 'Medium',
    'revision.hard': 'Hard',
    'revision.created': 'Revision created successfully',
    'revision.updated': 'Revision updated successfully',
    'revision.deleted': 'Revision deleted successfully',
    'revision.confirmDelete': 'Are you sure you want to delete this revision?',
    'revision.editRevision': 'Edit Revision',
    'revision.saveRevision': 'Save Revision',
    'revision.cancelRevision': 'Cancel',
    
    'flashcards.title': 'Flashcards',
    'flashcards.subtitle': 'Smart flashcard study system',
    'flashcards.loading': 'Loading...',
    'flashcards.createDeck': 'Create Deck',
    'flashcards.importDeck': 'Import Deck',
    'flashcards.totalDecks': 'Total Decks',
    'flashcards.totalCards': 'Total Cards',
    'flashcards.toReview': 'To Review',
    'flashcards.searchDecks': 'Search decks...',
    'flashcards.myDecks': 'My Decks',
    'flashcards.noDecksFound': 'No decks found',
    'flashcards.noDecksCreate': 'No decks created yet. Create your first deck!',
    'flashcards.cards': 'cards',
    'flashcards.toReviewShort': 'review',
    'flashcards.confirmDelete': 'Are you sure you want to delete this deck?',
    'flashcards.statistics': 'Statistics',
    'flashcards.studyProgress': 'Study Progress',
    'flashcards.performance': 'Performance',
    'flashcards.deckName': 'Deck Name',
    'flashcards.deckDescription': 'Deck Description',
    'flashcards.createCard': 'Create Card',
    'flashcards.editCard': 'Edit Card',
    'flashcards.front': 'Front',
    'flashcards.back': 'Back',
    'flashcards.addCard': 'Add Card',
    'flashcards.saveCard': 'Save Card',
    'flashcards.deleteCard': 'Delete Card',
    'flashcards.studyDeck': 'Study Deck',
    'flashcards.showAnswer': 'Show Answer',
    'flashcards.again': 'Again',
    'flashcards.good': 'Good',
    'flashcards.easy': 'Easy',
    'flashcards.studyComplete': 'Study Complete!',
    'flashcards.noCardsToReview': 'No cards to review',
    'flashcards.deckCreated': 'Deck created successfully',
    'flashcards.deckUpdated': 'Deck updated successfully',
    'flashcards.deckDeleted': 'Deck deleted successfully',
    'flashcards.cardCreated': 'Card created successfully',
    'flashcards.cardUpdated': 'Card updated successfully',
    'flashcards.cardDeleted': 'Card deleted successfully',
    
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.placeholder': 'Select a language',
    'settings.portuguese': 'Portuguese',
    'settings.english': 'English',
    'settings.spanish': 'Spanish',
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Configure your notification preferences',
    'settings.emailNotifications': 'Email notifications',
    'settings.pushNotifications': 'Push notifications',
    'settings.pushNotifications.desc': 'Receive notifications on your device',
    'settings.saveChanges': 'Save changes',
    'settings.changesSaved': 'Changes saved successfully!',
    'settings.changesSaved.desc': 'Your settings have been updated',
    'settings.study': 'Study',
    'settings.study.reminders': 'Study Reminders',
    'settings.study.reminders.desc': 'Get reminders for your study sessions',
    'settings.study.autoBackup': 'Auto Backup',
    'settings.study.autoBackup.desc': 'Automatically backup your data',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Customize the app appearance',
    'settings.appearance.theme': 'Theme',
    'settings.appearance.darkMode': 'Dark Mode',
    'settings.appearance.lightMode': 'Light Mode',
    'settings.appearance.systemMode': 'Follow System',
    'settings.darkMode': 'Dark Mode',
    'settings.darkMode.desc': 'Toggle between light and dark mode',
    'settings.studyReminders': 'Study Reminders',
    'settings.studyReminders.desc': 'Get reminders for your study sessions',
    'settings.pomodoro': 'Pomodoro',
    'settings.pomodoro.desc': 'Configure your focus sessions',
    'settings.focusTime': 'Focus Time (min)',
    'settings.shortBreak': 'Short Break (min)',
    'settings.longBreak': 'Long Break (min)',
    'settings.longBreakInterval': 'Long Break Interval',
    'settings.autoStartBreaks': 'Auto Start Breaks',
    'settings.autoStartBreaks.desc': 'Automatically start breaks after focus',
    'settings.resetData': 'Reset Data',
    'settings.resetData.desc': 'Reset or clear your data',
    'settings.deleteSchedule': 'Delete Schedule',
    'settings.deleteSchedule.btn': 'Delete Schedule',
    'settings.deleteAllData': 'Delete All Data',
    'settings.deleteAllData.btn': 'Delete All Data',
    'settings.scheduleDeleted': 'Schedule deleted',
    'settings.scheduleDeleted.desc': 'All events have been removed',
    'settings.allDataDeleted': 'All data deleted',
    'settings.allDataDeleted.desc': 'All data has been removed',
    'settings.general': 'General',
    'settings.account': 'Account',
    'settings.privacy': 'Privacy',
    'settings.about': 'About',
    
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfo.desc': 'Manage your personal and contact information',
    'profile.name': 'Name',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.firstName.placeholder': 'Enter your first name',
    'profile.lastName.placeholder': 'Enter your last name',
    'profile.email': 'Email',
    'profile.email.placeholder': 'Enter your email',
    'profile.phone': 'Phone',
    'profile.phone.placeholder': 'Enter your phone number',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Tell us about yourself',
    'profile.preferences': 'Preferences',
    'profile.theme': 'Theme',
    'profile.light': 'Light',
    'profile.dark': 'Dark',
    'profile.system': 'System',
    'profile.saveChanges': 'Save changes',
    'profile.changesSaved': 'Changes saved successfully!',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.currentPassword.placeholder': 'Enter your current password',
    'profile.newPassword.placeholder': 'Enter your new password',
    'profile.confirmPassword.placeholder': 'Confirm your new password',
    'profile.passwordChanged': 'Password changed successfully',
    'profile.profileUpdated': 'Profile updated successfully',
    'profile.uploadPhoto': 'Change profile photo',
    'profile.removePhoto': 'Remove photo',
    'profile.photoUpdated': 'Photo updated successfully',
    
    // Common buttons and actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.loading': 'Loading...',
    'common.noData': 'No data found',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.retry': 'Retry',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
  },
  es: {
    'navigation.dashboard': 'Panel',
    'navigation.calendar': 'Calendario',
    'navigation.schedule': 'Horario',
    'navigation.revision': 'Revisión',
    'navigation.flashcards': 'Tarjetas',
    'navigation.settings': 'Configuración',
    'navigation.profile': 'Perfil',
    
    'dashboard.title': 'Panel',
    'dashboard.todayTasks': 'Tareas de Hoy',
    'dashboard.noRevisionsToday': '¡No hay revisiones para hoy! 🎉',
    'dashboard.start': 'Iniciar',
    'dashboard.complete': 'Completar',
    'dashboard.postpone': 'Posponer',
    'dashboard.dailyProgress': 'Progreso Diario',
    'dashboard.tasks': 'tareas',
    'dashboard.weeklyProgress': 'Progreso Semanal',
    'dashboard.upcomingRevisions': 'Próximas Revisiones',
    'dashboard.overdue': 'Atrasadas',
    'dashboard.today': 'Hoy',
    'dashboard.thisWeek': 'Esta Semana',
    'dashboard.overview': 'Resumen',
    'dashboard.studyStats': 'Estadísticas de Estudio',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.createRevision': 'Crear Revisión',
    'dashboard.createFlashcard': 'Crear Tarjeta',
    'dashboard.scheduleEvent': 'Programar Evento',
    
    'schedule.title': 'Horario',
    'schedule.subtitle': 'Gestiona tu agenda y eventos',
    'schedule.newEvent': 'Nuevo Evento',
    'schedule.createEvent': 'Crear Evento',
    'schedule.editEvent': 'Editar Evento',
    'schedule.deleteEvent': 'Eliminar Evento',
    'schedule.eventTitle': 'Título del Evento',
    'schedule.eventDescription': 'Descripción del Evento',
    'schedule.eventDate': 'Fecha del Evento',
    'schedule.eventTime': 'Hora del Evento',
    'schedule.eventType': 'Tipo de Evento',
    'schedule.eventLocation': 'Ubicación del Evento',
    'schedule.saveEvent': 'Guardar Evento',
    'schedule.cancelEvent': 'Cancelar',
    'schedule.todayEvents': 'Eventos de Hoy',
    'schedule.noEventsToday': 'No hay eventos para hoy',
    'schedule.upcomingEvents': 'Próximos Eventos',
    'schedule.noUpcomingEvents': 'No hay eventos próximos',
    'schedule.allEvents': 'Todos los Eventos',
    'schedule.thisWeek': 'Esta Semana',
    'schedule.nextWeek': 'Próxima Semana',
    'schedule.calendar': 'Calendario',
    'schedule.agenda': 'Agenda',
    'schedule.eventCreated': 'Evento creado exitosamente',
    'schedule.eventUpdated': 'Evento actualizado exitosamente',
    'schedule.eventDeleted': 'Evento eliminado exitosamente',
    'schedule.confirmDelete': '¿Estás seguro de que quieres eliminar este evento?',
    'schedule.noEvents': 'No se encontraron eventos',
    'schedule.addEvent': 'Agregar Evento',
    'schedule.viewEvent': 'Ver Evento',
    'schedule.eventDetails': 'Detalles del Evento',
    'schedule.repeatEvent': 'Repetir Evento',
    'schedule.reminderTime': 'Recordatorio',
    'schedule.priority': 'Prioridad',
    'schedule.high': 'Alta',
    'schedule.medium': 'Media',
    'schedule.low': 'Baja',
    'schedule.today': 'Hoy',
    'schedule.day': 'Día',
    'schedule.week': 'Semana',
    'schedule.month': 'Mes',
    
    'revision.title': 'Sistema de Revisión',
    'revision.subtitle': 'Gestiona tus materiales de estudio con repetición espaciada',
    'revision.createRevision': 'Crear Revisión',
    'revision.createNew': 'Crear Nueva',
    'revision.myRevisions': 'Mis Revisiones',
    'revision.pending': 'Pendientes',
    'revision.priority': 'Prioridad',
    'revision.completed': 'Completadas',
    'revision.all': 'Todas',
    'revision.noRevisions': 'No se encontraron revisiones',
    'revision.searchPlaceholder': 'Buscar revisiones...',
    'revision.dueToday': 'Vence Hoy',
    'revision.overdue': 'Atrasadas',
    'revision.upcoming': 'Próximas',
    'revision.statistics': 'Estadísticas',
    'revision.totalRevisions': 'Total de Revisiones',
    'revision.completedToday': 'Completadas Hoy',
    'revision.pendingReview': 'Pendientes de Revisión',
    'revision.forToday': 'Para Hoy',
    'revision.revisionsFor': 'Revisiones para',
    'revision.noRevisionsToday': '¡No hay revisiones para hoy! 🎉',
    'revision.noUpcomingRevisions': 'No hay revisiones próximas',
    'revision.noCompletedRevisions': 'No hay revisiones completadas',
    'revision.viewContent': 'Ver Contenido',
    'revision.complete': 'Completar',
    'revision.postpone': 'Posponer',
    'revision.delete': 'Eliminar',
    'revision.title.placeholder': 'Título de la revisión',
    'revision.content.placeholder': 'Contenido de la revisión',
    'revision.tags.placeholder': 'Etiquetas (separadas por coma)',
    'revision.difficulty': 'Dificultad',
    'revision.easy': 'Fácil',
    'revision.medium': 'Medio',
    'revision.hard': 'Difícil',
    'revision.created': 'Revisión creada exitosamente',
    'revision.updated': 'Revisión actualizada exitosamente',
    'revision.deleted': 'Revisión eliminada exitosamente',
    'revision.confirmDelete': '¿Estás seguro de que quieres eliminar esta revisión?',
    'revision.editRevision': 'Editar Revisión',
    'revision.saveRevision': 'Guardar Revisión',
    'revision.cancelRevision': 'Cancelar',
    
    'flashcards.title': 'Tarjetas',
    'flashcards.subtitle': 'Sistema de estudio con tarjetas inteligentes',
    'flashcards.loading': 'Cargando...',
    'flashcards.createDeck': 'Crear Mazo',
    'flashcards.importDeck': 'Importar Mazo',
    'flashcards.totalDecks': 'Total de Mazos',
    'flashcards.totalCards': 'Total de Tarjetas',
    'flashcards.toReview': 'Para Revisar',
    'flashcards.searchDecks': 'Buscar mazos...',
    'flashcards.myDecks': 'Mis Mazos',
    'flashcards.noDecksFound': 'No se encontraron mazos',
    'flashcards.noDecksCreate': '¡Aún no se han creado mazos. Crea tu primer mazo!',
    'flashcards.cards': 'tarjetas',
    'flashcards.toReviewShort': 'revisar',
    'flashcards.confirmDelete': '¿Estás seguro de que quieres eliminar este mazo?',
    'flashcards.statistics': 'Estadísticas',
    'flashcards.studyProgress': 'Progreso de Estudio',
    'flashcards.performance': 'Rendimiento',
    'flashcards.deckName': 'Nombre del Mazo',
    'flashcards.deckDescription': 'Descripción del Mazo',
    'flashcards.createCard': 'Crear Tarjeta',
    'flashcards.editCard': 'Editar Tarjeta',
    'flashcards.front': 'Frente',
    'flashcards.back': 'Reverso',
    'flashcards.addCard': 'Agregar Tarjeta',
    'flashcards.saveCard': 'Guardar Tarjeta',
    'flashcards.deleteCard': 'Eliminar Tarjeta',
    'flashcards.studyDeck': 'Estudiar Mazo',
    'flashcards.showAnswer': 'Mostrar Respuesta',
    'flashcards.again': 'Otra vez',
    'flashcards.good': 'Bien',
    'flashcards.easy': 'Fácil',
    'flashcards.studyComplete': '¡Estudio Completo!',
    'flashcards.noCardsToReview': 'No hay tarjetas para revisar',
    'flashcards.deckCreated': 'Mazo creado exitosamente',
    'flashcards.deckUpdated': 'Mazo actualizado exitosamente',
    'flashcards.deckDeleted': 'Mazo eliminado exitosamente',
    'flashcards.cardCreated': 'Tarjeta creada exitosamente',
    'flashcards.cardUpdated': 'Tarjeta actualizada exitosamente',
    'flashcards.cardDeleted': 'Tarjeta eliminada exitosamente',
    
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Selecciona un idioma',
    'settings.portuguese': 'Portugués',
    'settings.english': 'Inglés',
    'settings.spanish': 'Español',
    'settings.notifications': 'Notificaciones',
    'settings.notifications.desc': 'Configura tus preferencias de notificación',
    'settings.emailNotifications': 'Notificaciones por correo',
    'settings.pushNotifications': 'Notificaciones push',
    'settings.pushNotifications.desc': 'Recibe notificaciones en tu dispositivo',
    'settings.saveChanges': 'Guardar cambios',
    'settings.changesSaved': '¡Cambios guardados con éxito!',
    'settings.changesSaved.desc': 'Tus configuraciones han sido actualizadas',
    'settings.study': 'Estudios',
    'settings.study.reminders': 'Recordatorios de Estudio',
    'settings.study.reminders.desc': 'Recibe recordatorios para tus sesiones de estudio',
    'settings.study.autoBackup': 'Respaldo Automático',
    'settings.study.autoBackup.desc': 'Respalda automáticamente tus datos',
    'settings.appearance': 'Apariencia',
    'settings.appearance.desc': 'Personaliza la apariencia de la aplicación',
    'settings.appearance.theme': 'Tema',
    'settings.appearance.darkMode': 'Modo Oscuro',
    'settings.appearance.lightMode': 'Modo Claro',
    'settings.appearance.systemMode': 'Seguir Sistema',
    'settings.darkMode': 'Modo Oscuro',
    'settings.darkMode.desc': 'Alterna entre modo claro y oscuro',
    'settings.studyReminders': 'Recordatorios de Estudio',
    'settings.studyReminders.desc': 'Recibe recordatorios para tus sesiones de estudio',
    'settings.pomodoro': 'Pomodoro',
    'settings.pomodoro.desc': 'Configura tus sesiones de enfoque',
    'settings.focusTime': 'Tiempo de Enfoque (min)',
    'settings.shortBreak': 'Pausa Corta (min)',
    'settings.longBreak': 'Pausa Larga (min)',
    'settings.longBreakInterval': 'Intervalo Pausa Larga',
    'settings.autoStartBreaks': 'Iniciar Pausas Automáticamente',
    'settings.autoStartBreaks.desc': 'Inicia pausas automáticamente después del enfoque',
    'settings.resetData': 'Restablecer Datos',
    'settings.resetData.desc': 'Restablece o limpia tus datos',
    'settings.deleteSchedule': 'Eliminar Horario',
    'settings.deleteSchedule.btn': 'Eliminar Horario',
    'settings.deleteAllData': 'Eliminar Todos los Datos',
    'settings.deleteAllData.btn': 'Eliminar Todos los Datos',
    'settings.scheduleDeleted': 'Horario eliminado',
    'settings.scheduleDeleted.desc': 'Todos los eventos han sido removidos',
    'settings.allDataDeleted': 'Todos los datos eliminados',
    'settings.allDataDeleted.desc': 'Todos los datos han sido removidos',
    'settings.general': 'General',
    'settings.account': 'Cuenta',
    'settings.privacy': 'Privacidad',
    'settings.about': 'Acerca de',
    
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.personalInfo.desc': 'Gestiona tu información personal y de contacto',
    'profile.name': 'Nombre',
    'profile.firstName': 'Primer Nombre',
    'profile.lastName': 'Apellido',
    'profile.firstName.placeholder': 'Ingresa tu primer nombre',
    'profile.lastName.placeholder': 'Ingresa tu apellido',
    'profile.email': 'Correo',
    'profile.email.placeholder': 'Ingresa tu correo',
    'profile.phone': 'Teléfono',
    'profile.phone.placeholder': 'Ingresa tu teléfono',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Cuéntanos sobre ti',
    'profile.preferences': 'Preferencias',
    'profile.theme': 'Tema',
    'profile.light': 'Claro',
    'profile.dark': 'Oscuro',
    'profile.system': 'Sistema',
    'profile.saveChanges': 'Guardar cambios',
    'profile.changesSaved': '¡Cambios guardados con éxito!',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.currentPassword': 'Contraseña Actual',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.confirmPassword': 'Confirmar Nueva Contraseña',
    'profile.currentPassword.placeholder': 'Ingresa tu contraseña actual',
    'profile.newPassword.placeholder': 'Ingresa tu nueva contraseña',
    'profile.confirmPassword.placeholder': 'Confirma tu nueva contraseña',
    'profile.passwordChanged': 'Contraseña cambiada exitosamente',
    'profile.profileUpdated': 'Perfil actualizado exitosamente',
    'profile.uploadPhoto': 'Cambiar foto de perfil',
    'profile.removePhoto': 'Quitar foto',
    'profile.photoUpdated': 'Foto actualizada exitosamente',
    
    // Botones y acciones comunes
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.close': 'Cerrar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.loading': 'Cargando...',
    'common.noData': 'No se encontraron datos',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.confirm': 'Confirmar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.apply': 'Aplicar',
    'common.reset': 'Restablecer',
    'common.clear': 'Limpiar',
    'common.select': 'Seleccionar',
    'common.upload': 'Subir',
    'common.download': 'Descargar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.refresh': 'Actualizar',
    'common.retry': 'Reintentar',
    'common.continue': 'Continuar',
    'common.finish': 'Finalizar',
    'common.start': 'Iniciar',
    'common.stop': 'Detener',
    'common.pause': 'Pausar',
    'common.resume': 'Reanudar',
    'common.settings': 'Configuraciones',
    'common.help': 'Ayuda',
    'common.about': 'Acerca de',
    'common.contact': 'Contacto',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  const setLanguage = (lang: string) => {
    console.log('🌐 Changing language to:', lang);
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Force re-render of all components
    setTimeout(() => {
      console.log('🌐 Language change completed:', lang);
      // Trigger a small state update to force component re-renders
      setLanguageState(prevLang => prevLang);
    }, 50);
  };

  const t = (key: string): string => {
    const languageTranslations = translations[language as keyof typeof translations];
    
    if (!languageTranslations) {
      console.warn(`🌐 Language not found: ${language}, falling back to 'pt'`);
      const fallbackTranslations = translations['pt'];
      const translation = fallbackTranslations?.[key as keyof typeof fallbackTranslations];
      return translation || key;
    }
    
    const translation = languageTranslations[key as keyof typeof languageTranslations];
    
    if (!translation) {
      console.warn(`🌐 Translation missing for key: ${key} in language: ${language}`);
      // Try fallback to Portuguese
      const fallbackTranslations = translations['pt'];
      const fallbackTranslation = fallbackTranslations?.[key as keyof typeof fallbackTranslations];
      return fallbackTranslation || key;
    }
    
    return translation;
  };

  useEffect(() => {
    console.log('🌐 Language context updated:', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
