import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useLocalStorage } from '../hooks/useLocalStorage';

type Language = 'pt' | 'en' | 'es' | 'zh' | 'ru' | 'fr' | 'it' | 'ar' | 'hi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// Traduções
const translations = {
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendário',
    'nav.schedule': 'Cronograma',
    'nav.revision': 'Revisão',
    'nav.flashcards': 'Flashcards',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Tarefas de Hoje',
    'dashboard.upcomingEvents': 'Próximos Eventos',
    'dashboard.studyProgress': 'Progresso dos Estudos',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.addTask': 'Adicionar Tarefa',
    'dashboard.addEvent': 'Adicionar Evento',
    'dashboard.startPomodoro': 'Iniciar Pomodoro',
    'dashboard.noTasks': 'Nenhuma tarefa para hoje',
    'dashboard.noEvents': 'Nenhum evento próximo',
    
    // Calendar
    'calendar.title': 'Calendário',
    'calendar.today': 'Hoje',
    'calendar.week': 'Semana',
    'calendar.month': 'Mês',
    'calendar.addEvent': 'Adicionar Evento',
    'calendar.noEvents': 'Nenhum evento',
    'calendar.allDay': 'Dia todo',
    
    // Flashcards
    'flashcards.title': 'Flashcards',
    'flashcards.myDecks': 'Meus Baralhos',
    'flashcards.createDeck': 'Criar Baralho',
    'flashcards.study': 'Estudar',
    'flashcards.cards': 'cartas',
    'flashcards.noDecks': 'Nenhum baralho criado',
    'flashcards.createFirst': 'Crie seu primeiro baralho para começar',
    'flashcards.studyMode': 'Modo de Estudo',
    'flashcards.showAnswer': 'Mostrar Resposta',
    'flashcards.nextCard': 'Próxima Carta',
    'flashcards.difficulty.again': 'Novamente',
    'flashcards.difficulty.hard': 'Difícil',
    'flashcards.difficulty.good': 'Bom',
    'flashcards.difficulty.easy': 'Fácil',
    
    // Revision
    'revision.title': 'Revisão',
    'revision.today': 'Hoje',
    'revision.upcoming': 'Próximas',
    'revision.overdue': 'Atrasadas',
    'revision.completed': 'Concluídas',
    'revision.addItem': 'Adicionar Item',
    'revision.noItems': 'Nenhum item de revisão',
    'revision.markComplete': 'Marcar como Concluído',
    'revision.postpone': 'Adiar',
    'revision.edit': 'Editar',
    'revision.delete': 'Excluir',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.appearance': 'Aparência',
    'settings.appearance.desc': 'Personalize a aparência do aplicativo',
    'settings.darkMode': 'Modo Escuro',
    'settings.darkMode.desc': 'Ativar tema escuro',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Selecione o idioma',
    
    'settings.notifications': 'Notificações',
    'settings.notifications.desc': 'Configure como você quer receber notificações',
    'settings.pushNotifications': 'Notificações Push',
    'settings.pushNotifications.desc': 'Receba notificações no navegador',
    'settings.studyReminders': 'Lembretes de Estudo',
    'settings.studyReminders.desc': 'Receba lembretes para suas sessões de estudo',
    
    'settings.pomodoro': 'Configurações do Pomodoro',
    'settings.pomodoro.desc': 'Configure os tempos do seu timer Pomodoro',
    'settings.focusTime': 'Tempo de Foco (min)',
    'settings.shortBreak': 'Pausa Curta (min)',
    'settings.longBreak': 'Pausa Longa (min)',
    'settings.autoStartBreaks': 'Iniciar Pausas Automaticamente',
    'settings.autoStartBreaks.desc': 'Iniciar pausas automaticamente após cada sessão',
    
    'settings.privacy': 'Privacidade e Segurança',
    'settings.privacy.desc': 'Configure suas preferências de privacidade',
    'settings.autoBackup': 'Backup Automático',
    'settings.autoBackup.desc': 'Salvar dados automaticamente na nuvem',
    'settings.changePassword': 'Alterar Senha',
    
    'settings.resetData': 'Redefinir Dados',
    'settings.resetData.desc': 'Redefina ou exporte seus dados do aplicativo',
    'settings.exportData': 'Exportar Dados',
    'settings.exportData.btn': 'Baixar Dados em JSON',
    'settings.resetSettings': 'Redefinir Configurações',
    'settings.resetSettings.btn': 'Restaurar Padrões',
    'settings.deleteAllData': 'Apagar Todos os Dados',
    'settings.deleteAllData.btn': 'Apagar Tudo Permanentemente',
    
    'common.save': 'Salvar Alterações',
    'common.cancel': 'Cancelar',
    'common.back': 'Voltar',
    'common.add': 'Adicionar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.close': 'Fechar',
    'common.confirm': 'Confirmar',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.personalInfo.desc': 'Configure suas informações pessoais',
    'profile.firstName': 'Nome',
    'profile.firstName.placeholder': 'Seu nome',
    'profile.lastName': 'Sobrenome',
    'profile.lastName.placeholder': 'Seu sobrenome',
    'profile.email': 'Email',
    'profile.email.placeholder': 'seu@email.com',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Fale um pouco sobre você...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendar',
    'nav.schedule': 'Schedule',
    'nav.revision': 'Revision',
    'nav.flashcards': 'Flashcards',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Today\'s Tasks',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.studyProgress': 'Study Progress',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addTask': 'Add Task',
    'dashboard.addEvent': 'Add Event',
    'dashboard.startPomodoro': 'Start Pomodoro',
    'dashboard.noTasks': 'No tasks for today',
    'dashboard.noEvents': 'No upcoming events',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.today': 'Today',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.addEvent': 'Add Event',
    'calendar.noEvents': 'No events',
    'calendar.allDay': 'All day',
    
    // Flashcards
    'flashcards.title': 'Flashcards',
    'flashcards.myDecks': 'My Decks',
    'flashcards.createDeck': 'Create Deck',
    'flashcards.study': 'Study',
    'flashcards.cards': 'cards',
    'flashcards.noDecks': 'No decks created',
    'flashcards.createFirst': 'Create your first deck to get started',
    'flashcards.studyMode': 'Study Mode',
    'flashcards.showAnswer': 'Show Answer',
    'flashcards.nextCard': 'Next Card',
    'flashcards.difficulty.again': 'Again',
    'flashcards.difficulty.hard': 'Hard',
    'flashcards.difficulty.good': 'Good',
    'flashcards.difficulty.easy': 'Easy',
    
    // Revision
    'revision.title': 'Revision',
    'revision.today': 'Today',
    'revision.upcoming': 'Upcoming',
    'revision.overdue': 'Overdue',
    'revision.completed': 'Completed',
    'revision.addItem': 'Add Item',
    'revision.noItems': 'No revision items',
    'revision.markComplete': 'Mark Complete',
    'revision.postpone': 'Postpone',
    'revision.edit': 'Edit',
    'revision.delete': 'Delete',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Customize the app appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.darkMode.desc': 'Enable dark theme',
    'settings.language': 'Language',
    'settings.language.placeholder': 'Select language',
    
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Configure how you want to receive notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotifications.desc': 'Receive notifications in browser',
    'settings.studyReminders': 'Study Reminders',
    'settings.studyReminders.desc': 'Receive reminders for your study sessions',
    
    'settings.pomodoro': 'Pomodoro Settings',
    'settings.pomodoro.desc': 'Configure your Pomodoro timer settings',
    'settings.focusTime': 'Focus Time (min)',
    'settings.shortBreak': 'Short Break (min)',
    'settings.longBreak': 'Long Break (min)',
    'settings.autoStartBreaks': 'Auto Start Breaks',
    'settings.autoStartBreaks.desc': 'Automatically start breaks after each session',
    
    'settings.privacy': 'Privacy & Security',
    'settings.privacy.desc': 'Configure your privacy preferences',
    'settings.autoBackup': 'Auto Backup',
    'settings.autoBackup.desc': 'Automatically save data to cloud',
    'settings.changePassword': 'Change Password',
    
    'settings.resetData': 'Reset Data',
    'settings.resetData.desc': 'Reset or export your app data',
    'settings.exportData': 'Export Data',
    'settings.exportData.btn': 'Download JSON Data',
    'settings.resetSettings': 'Reset Settings',
    'settings.resetSettings.btn': 'Restore Defaults',
    'settings.deleteAllData': 'Delete All Data',
    'settings.deleteAllData.btn': 'Delete Everything Permanently',
    
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfo.desc': 'Configure your personal information',
    'profile.firstName': 'First Name',
    'profile.firstName.placeholder': 'Your first name',
    'profile.lastName': 'Last Name',
    'profile.lastName.placeholder': 'Your last name',
    'profile.email': 'Email',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Tell us about yourself...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendario',
    'nav.schedule': 'Horario',
    'nav.revision': 'Revisión',
    'nav.flashcards': 'Tarjetas',
    'nav.settings': 'Configuración',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Tareas de Hoy',
    'dashboard.upcomingEvents': 'Próximos Eventos',
    'dashboard.studyProgress': 'Progreso de Estudios',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.addTask': 'Agregar Tarea',
    'dashboard.addEvent': 'Agregar Evento',
    'dashboard.startPomodoro': 'Iniciar Pomodoro',
    'dashboard.noTasks': 'No hay tareas para hoy',
    'dashboard.noEvents': 'No hay eventos próximos',
    
    // Calendar
    'calendar.title': 'Calendario',
    'calendar.today': 'Hoy',
    'calendar.week': 'Semana',
    'calendar.month': 'Mes',
    'calendar.addEvent': 'Agregar Evento',
    'calendar.noEvents': 'No hay eventos',
    'calendar.allDay': 'Todo el día',
    
    // Flashcards
    'flashcards.title': 'Tarjetas',
    'flashcards.myDecks': 'Mis Mazos',
    'flashcards.createDeck': 'Crear Mazo',
    'flashcards.study': 'Estudiar',
    'flashcards.cards': 'tarjetas',
    'flashcards.noDecks': 'No hay mazos creados',
    'flashcards.createFirst': 'Crea tu primer mazo para comenzar',
    'flashcards.studyMode': 'Modo de Estudio',
    'flashcards.showAnswer': 'Mostrar Respuesta',
    'flashcards.nextCard': 'Siguiente Tarjeta',
    'flashcards.difficulty.again': 'Otra vez',
    'flashcards.difficulty.hard': 'Difícil',
    'flashcards.difficulty.good': 'Bueno',
    'flashcards.difficulty.easy': 'Fácil',
    
    // Revision
    'revision.title': 'Revisión',
    'revision.today': 'Hoy',
    'revision.upcoming': 'Próximas',
    'revision.overdue': 'Atrasadas',
    'revision.completed': 'Completadas',
    'revision.addItem': 'Agregar Elemento',
    'revision.noItems': 'No hay elementos de revisión',
    'revision.markComplete': 'Marcar como Completado',
    'revision.postpone': 'Posponer',
    'revision.edit': 'Editar',
    'revision.delete': 'Eliminar',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.appearance': 'Apariencia',
    'settings.appearance.desc': 'Personaliza la apariencia de la aplicación',
    'settings.darkMode': 'Modo Oscuro',
    'settings.darkMode.desc': 'Activar tema oscuro',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Seleccionar idioma',
    
    'settings.notifications': 'Notificaciones',
    'settings.notifications.desc': 'Configura cómo quieres recibir notificaciones',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.pushNotifications.desc': 'Recibir notificaciones en el navegador',
    'settings.studyReminders': 'Recordatorios de Estudio',
    'settings.studyReminders.desc': 'Recibir recordatorios para tus sesiones de estudio',
    
    'settings.pomodoro': 'Configuración de Pomodoro',
    'settings.pomodoro.desc': 'Configura los tiempos de tu temporizador Pomodoro',
    'settings.focusTime': 'Tiempo de Concentración (min)',
    'settings.shortBreak': 'Pausa Corta (min)',
    'settings.longBreak': 'Pausa Larga (min)',
    'settings.autoStartBreaks': 'Iniciar Pausas Automáticamente',
    'settings.autoStartBreaks.desc': 'Iniciar pausas automáticamente después de cada sesión',
    
    'settings.privacy': 'Privacidad y Seguridad',
    'settings.privacy.desc': 'Configure sus preferencias de privacidad',
    'settings.autoBackup': 'Respaldo Automático',
    'settings.autoBackup.desc': 'Guardar datos automáticamente en la nube',
    'settings.changePassword': 'Cambiar Contraseña',
    
    'settings.resetData': 'Restablecer Datos',
    'settings.resetData.desc': 'Restablece o exporta los datos de tu aplicación',
    'settings.exportData': 'Exportar Datos',
    'settings.exportData.btn': 'Descargar Datos en JSON',
    'settings.resetSettings': 'Restablecer Configuración',
    'settings.resetSettings.btn': 'Restaurar Valores Predeterminados',
    'settings.deleteAllData': 'Eliminar Todos los Datos',
    'settings.deleteAllData.btn': 'Eliminar Todo Permanentemente',
    
    'common.save': 'Guardar Cambios',
    'common.cancel': 'Cancelar',
    'common.back': 'Volver',
    'common.add': 'Agregar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.personalInfo.desc': 'Configura tu información personal',
    'profile.firstName': 'Nombre',
    'profile.firstName.placeholder': 'Tu nombre',
    'profile.lastName': 'Apellido',
    'profile.lastName.placeholder': 'Tu apellido',
    'profile.email': 'Email',
    'profile.email.placeholder': 'tu@email.com',
    'profile.bio': 'Biografía',
    'profile.bio.placeholder': 'Cuéntanos sobre ti...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.calendar': '日历',
    'nav.schedule': '时间表',
    'nav.revision': '复习',
    'nav.flashcards': '抽认卡',
    'nav.settings': '设置',
    'nav.profile': '个人资料',
    
    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.todayTasks': '今日任务',
    'dashboard.upcomingEvents': '即将发生的事件',
    'dashboard.studyProgress': '学习进度',
    'dashboard.quickActions': '快速操作',
    'dashboard.addTask': '添加任务',
    'dashboard.addEvent': '添加事件',
    'dashboard.startPomodoro': '开始番茄钟',
    'dashboard.noTasks': '今日无任务',
    'dashboard.noEvents': '无即将发生的事件',
    
    // Calendar
    'calendar.title': '日历',
    'calendar.today': '今天',
    'calendar.week': '周',
    'calendar.month': '月',
    'calendar.addEvent': '添加事件',
    'calendar.noEvents': '无事件',
    'calendar.allDay': '全天',
    
    // Flashcards
    'flashcards.title': '抽认卡',
    'flashcards.myDecks': '我的牌组',
    'flashcards.createDeck': '创建牌组',
    'flashcards.study': '学习',
    'flashcards.cards': '张牌',
    'flashcards.noDecks': '无已创建牌组',
    'flashcards.createFirst': '创建你的第一个牌组开始学习',
    'flashcards.studyMode': '学习模式',
    'flashcards.showAnswer': '显示答案',
    'flashcards.nextCard': '下一张牌',
    'flashcards.difficulty.again': '再来一次',
    'flashcards.difficulty.hard': '困难',
    'flashcards.difficulty.good': '好',
    'flashcards.difficulty.easy': '简单',
    
    // Revision
    'revision.title': '复习',
    'revision.today': '今天',
    'revision.upcoming': '即将到来',
    'revision.overdue': '逾期',
    'revision.completed': '已完成',
    'revision.addItem': '添加项目',
    'revision.noItems': '无复习项目',
    'revision.markComplete': '标记为完成',
    'revision.postpone': '推迟',
    'revision.edit': '编辑',
    'revision.delete': '删除',
    
    // Settings
    'settings.title': '设置',
    'settings.appearance': '外观',
    'settings.appearance.desc': '自定义应用程序外观',
    'settings.darkMode': '深色模式',
    'settings.darkMode.desc': '启用深色主题',
    'settings.language': '语言',
    'settings.language.placeholder': '选择语言',
    
    'settings.notifications': '通知',
    'settings.notifications.desc': '配置您想要接收通知的方式',
    'settings.pushNotifications': '推送通知',
    'settings.pushNotifications.desc': '在浏览器中接收通知',
    'settings.studyReminders': '学习提醒',
    'settings.studyReminders.desc': '接收学习会话提醒',
    
    'settings.pomodoro': '番茄工作法设置',
    'settings.pomodoro.desc': '配置您的番茄工作法计时器设置',
    'settings.focusTime': '专注时间（分钟）',
    'settings.shortBreak': '短暂休息（分钟）',
    'settings.longBreak': '长时间休息（分钟）',
    'settings.autoStartBreaks': '自动开始休息',
    'settings.autoStartBreaks.desc': '每次会话后自动开始休息',
    
    'settings.privacy': '隐私与安全',
    'settings.privacy.desc': '配置您的隐私偏好',
    'settings.autoBackup': '自动备份',
    'settings.autoBackup.desc': '自动将数据保存到云端',
    'settings.changePassword': '更改密码',
    
    'settings.resetData': '重置数据',
    'settings.resetData.desc': '重置或导出您的应用数据',
    'settings.exportData': '导出数据',
    'settings.exportData.btn': '下载JSON数据',
    'settings.resetSettings': '重置设置',
    'settings.resetSettings.btn': '恢复默认设置',
    'settings.deleteAllData': '删除所有数据',
    'settings.deleteAllData.btn': '永久删除所有内容',
    
    'common.save': '保存更改',
    'common.cancel': '取消',
    'common.back': '返回',
    
    // Profile
    'profile.title': '个人资料',
    'profile.personalInfo': '个人信息',
    'profile.personalInfo.desc': '配置您的个人信息',
    'profile.firstName': '名字',
    'profile.firstName.placeholder': '您的名字',
    'profile.lastName': '姓氏',
    'profile.lastName.placeholder': '您的姓氏',
    'profile.email': '电子邮件',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': '简介',
    'profile.bio.placeholder': '告诉我们您的情况...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель управления',
    'nav.calendar': 'Календарь',
    'nav.schedule': 'Расписание',
    'nav.revision': 'Повторение',
    'nav.flashcards': 'Флэш-карты',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    
    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.todayTasks': 'Задачи на сегодня',
    'dashboard.upcomingEvents': 'Предстоящие события',
    'dashboard.studyProgress': 'Прогресс обучения',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.addTask': 'Добавить задачу',
    'dashboard.addEvent': 'Добавить событие',
    'dashboard.startPomodoro': 'Начать Помодоро',
    'dashboard.noTasks': 'Нет задач на сегодня',
    'dashboard.noEvents': 'Нет предстоящих событий',
    
    // Calendar
    'calendar.title': 'Календарь',
    'calendar.today': 'Сегодня',
    'calendar.week': 'Неделя',
    'calendar.month': 'Месяц',
    'calendar.addEvent': 'Добавить событие',
    'calendar.noEvents': 'Нет событий',
    'calendar.allDay': 'Весь день',
    
    // Flashcards
    'flashcards.title': 'Флэш-карты',
    'flashcards.myDecks': 'Мои колоды',
    'flashcards.createDeck': 'Создать колоду',
    'flashcards.study': 'Учить',
    'flashcards.cards': 'карты',
    'flashcards.noDecks': 'Колоды не созданы',
    'flashcards.createFirst': 'Создайте первую колоду, чтобы начать',
    'flashcards.studyMode': 'Режим обучения',
    'flashcards.showAnswer': 'Показать ответ',
    'flashcards.nextCard': 'Следующая карта',
    'flashcards.difficulty.again': 'Снова',
    'flashcards.difficulty.hard': 'Сложно',
    'flashcards.difficulty.good': 'Хорошо',
    'flashcards.difficulty.easy': 'Легко',
    
    // Revision
    'revision.title': 'Повторение',
    'revision.today': 'Сегодня',
    'revision.upcoming': 'Предстоящие',
    'revision.overdue': 'Просроченные',
    'revision.completed': 'Завершённые',
    'revision.addItem': 'Добавить элемент',
    'revision.noItems': 'Нет элементов для повторения',
    'revision.markComplete': 'Отметить как выполненное',
    'revision.postpone': 'Отложить',
    'revision.edit': 'Редактировать',
    'revision.delete': 'Удалить',
    
    // Settings
    'settings.title': 'Настройки',
    'settings.appearance': 'Внешний вид',
    'settings.appearance.desc': 'Настройте внешний вид приложения',
    'settings.darkMode': 'Тёмная тема',
    'settings.darkMode.desc': 'Включить тёмную тему',
    'settings.language': 'Язык',
    'settings.language.placeholder': 'Выберите язык',
    
    'settings.notifications': 'Уведомления',
    'settings.notifications.desc': 'Настройте способ получения уведомлений',
    'settings.pushNotifications': 'Push-уведомления',
    'settings.pushNotifications.desc': 'Получать уведомления в браузере',
    'settings.studyReminders': 'Напоминания об учебе',
    'settings.studyReminders.desc': 'Получать напоминания о ваших учебных сессиях',
    
    'settings.pomodoro': 'Настройки Помодоро',
    'settings.pomodoro.desc': 'Настройте параметры таймера Помодоро',
    'settings.focusTime': 'Время концентрации (мин)',
    'settings.shortBreak': 'Короткий перерыв (мин)',
    'settings.longBreak': 'Длинный перерыв (мин)',
    'settings.autoStartBreaks': 'Автоматически начинать перерывы',
    'settings.autoStartBreaks.desc': 'Автоматически начинать перерывы после каждой сессии',
    
    'settings.privacy': 'Конфиденциальность и безопасность',
    'settings.privacy.desc': 'Настройте ваши предпочтения конфиденциальности',
    'settings.autoBackup': 'Автоматическое резервное копирование',
    'settings.autoBackup.desc': 'Автоматически сохранять данные в облаке',
    'settings.changePassword': 'Изменить пароль',
    
    'settings.resetData': 'Сброс данных',
    'settings.resetData.desc': 'Сбросить или экспортировать данные приложения',
    'settings.exportData': 'Экспорт данных',
    'settings.exportData.btn': 'Скачать данные JSON',
    'settings.resetSettings': 'Сброс настроек',
    'settings.resetSettings.btn': 'Восстановить по умолчанию',
    'settings.deleteAllData': 'Удалить все данные',
    'settings.deleteAllData.btn': 'Удалить все навсегда',
    
    'common.save': 'Сохранить изменения',
    'common.cancel': 'Отмена',
    'common.back': 'Назад',
    
    // Profile
    'profile.title': 'Профиль',
    'profile.personalInfo': 'Личная информация',
    'profile.personalInfo.desc': 'Настройте вашу личную информацию',
    'profile.firstName': 'Имя',
    'profile.firstName.placeholder': 'Ваше имя',
    'profile.lastName': 'Фамилия',
    'profile.lastName.placeholder': 'Ваша фамилия',
    'profile.email': 'Электронная почта',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'Биография',
    'profile.bio.placeholder': 'Расскажите нам о себе...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.calendar': 'Calendrier',
    'nav.schedule': 'Horaire',
    'nav.revision': 'Révision',
    'nav.flashcards': 'Cartes mémoire',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.todayTasks': 'Tâches du jour',
    'dashboard.upcomingEvents': 'Événements à venir',
    'dashboard.studyProgress': 'Progression des études',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.addTask': 'Ajouter une tâche',
    'dashboard.addEvent': 'Ajouter un événement',
    'dashboard.startPomodoro': 'Démarrer Pomodoro',
    'dashboard.noTasks': 'Aucune tâche pour aujourd\'hui',
    'dashboard.noEvents': 'Aucun événement à venir',
    
    // Calendar
    'calendar.title': 'Calendrier',
    'calendar.today': 'Aujourd\'hui',
    'calendar.week': 'Semaine',
    'calendar.month': 'Mois',
    'calendar.addEvent': 'Ajouter un événement',
    'calendar.noEvents': 'Aucun événement',
    'calendar.allDay': 'Toute la journée',
    
    // Flashcards
    'flashcards.title': 'Cartes mémoire',
    'flashcards.myDecks': 'Mes jeux',
    'flashcards.createDeck': 'Créer un jeu',
    'flashcards.study': 'Étudier',
    'flashcards.cards': 'cartes',
    'flashcards.noDecks': 'Aucun jeu créé',
    'flashcards.createFirst': 'Créez votre premier jeu pour commencer',
    'flashcards.studyMode': 'Mode d\'étude',
    'flashcards.showAnswer': 'Afficher la réponse',
    'flashcards.nextCard': 'Carte suivante',
    'flashcards.difficulty.again': 'Encore',
    'flashcards.difficulty.hard': 'Difficile',
    'flashcards.difficulty.good': 'Bien',
    'flashcards.difficulty.easy': 'Facile',
    
    // Revision
    'revision.title': 'Révision',
    'revision.today': 'Aujourd\'hui',
    'revision.upcoming': 'À venir',
    'revision.overdue': 'En retard',
    'revision.completed': 'Terminées',
    'revision.addItem': 'Ajouter un élément',
    'revision.noItems': 'Aucun élément de révision',
    'revision.markComplete': 'Marquer comme terminé',
    'revision.postpone': 'Reporter',
    'revision.edit': 'Modifier',
    'revision.delete': 'Supprimer',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.appearance': 'Apparence',
    'settings.appearance.desc': 'Personnalisez l\'apparence de l\'application',
    'settings.darkMode': 'Mode sombre',
    'settings.darkMode.desc': 'Activer le thème sombre',
    'settings.language': 'Langue',
    'settings.language.placeholder': 'Sélectionner la langue',
    
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Configurez la façon dont vous souhaitez recevoir les notifications',
    'settings.pushNotifications': 'Notifications push',
    'settings.pushNotifications.desc': 'Recevoir des notifications dans le navigateur',
    'settings.studyReminders': 'Rappels d\'étude',
    'settings.studyReminders.desc': 'Recevoir des rappels pour vos sessions d\'étude',
    
    'settings.pomodoro': 'Paramètres Pomodoro',
    'settings.pomodoro.desc': 'Configurez les paramètres de votre minuteur Pomodoro',
    'settings.focusTime': 'Temps de concentration (min)',
    'settings.shortBreak': 'Pause courte (min)',
    'settings.longBreak': 'Pause longue (min)',
    'settings.autoStartBreaks': 'Démarrer automatiquement les pauses',
    'settings.autoStartBreaks.desc': 'Démarrer automatiquement les pauses après chaque session',
    
    'settings.privacy': 'Confidentialité et sécurité',
    'settings.privacy.desc': 'Configurez vos préférences de confidentialité',
    'settings.autoBackup': 'Sauvegarde automatique',
    'settings.autoBackup.desc': 'Sauvegarder automatiquement les données dans le cloud',
    'settings.changePassword': 'Changer le mot de passe',
    
    'settings.resetData': 'Réinitialiser les données',
    'settings.resetData.desc': 'Réinitialisez ou exportez les données de votre application',
    'settings.exportData': 'Exporter les données',
    'settings.exportData.btn': 'Télécharger les données JSON',
    'settings.resetSettings': 'Réinitialiser les paramètres',
    'settings.resetSettings.btn': 'Restaurer les valeurs par défaut',
    'settings.deleteAllData': 'Supprimer toutes les données',
    'settings.deleteAllData.btn': 'Tout supprimer définitivement',
    
    'common.save': 'Enregistrer les modifications',
    'common.cancel': 'Annuler',
    'common.back': 'Retour',
    
    // Profile
    'profile.title': 'Profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.personalInfo.desc': 'Configurez vos informations personnelles',
    'profile.firstName': 'Prénom',
    'profile.firstName.placeholder': 'Votre prénom',
    'profile.lastName': 'Nom de famille',
    'profile.lastName.placeholder': 'Votre nom de famille',
    'profile.email': 'E-mail',
    'profile.email.placeholder': 'votre@email.com',
    'profile.bio': 'Biographie',
    'profile.bio.placeholder': 'Parlez-nous de vous...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  it: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendario',
    'nav.schedule': 'Orario',
    'nav.revision': 'Revisione',
    'nav.flashcards': 'Flashcard',
    'nav.settings': 'Impostazioni',
    'nav.profile': 'Profilo',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Compiti di oggi',
    'dashboard.upcomingEvents': 'Eventi imminenti',
    'dashboard.studyProgress': 'Progresso dello studio',
    'dashboard.quickActions': 'Azioni rapide',
    'dashboard.addTask': 'Aggiungi compito',
    'dashboard.addEvent': 'Aggiungi evento',
    'dashboard.startPomodoro': 'Avvia Pomodoro',
    'dashboard.noTasks': 'Nessun compito per oggi',
    'dashboard.noEvents': 'Nessun evento imminente',
    
    // Calendar
    'calendar.title': 'Calendario',
    'calendar.today': 'Oggi',
    'calendar.week': 'Settimana',
    'calendar.month': 'Mese',
    'calendar.addEvent': 'Aggiungi evento',
    'calendar.noEvents': 'Nessun evento',
    'calendar.allDay': 'Tutto il giorno',
    
    // Flashcards
    'flashcards.title': 'Flashcard',
    'flashcards.myDecks': 'I miei mazzi',
    'flashcards.createDeck': 'Crea mazzo',
    'flashcards.study': 'Studia',
    'flashcards.cards': 'carte',
    'flashcards.noDecks': 'Nessun mazzo creato',
    'flashcards.createFirst': 'Crea il tuo primo mazzo per iniziare',
    'flashcards.studyMode': 'Modalità di studio',
    'flashcards.showAnswer': 'Mostra risposta',
    'flashcards.nextCard': 'Carta successiva',
    'flashcards.difficulty.again': 'Ancora',
    'flashcards.difficulty.hard': 'Difficile',
    'flashcards.difficulty.good': 'Buono',
    'flashcards.difficulty.easy': 'Facile',
    
    // Revision
    'revision.title': 'Revisione',
    'revision.today': 'Oggi',
    'revision.upcoming': 'Imminenti',
    'revision.overdue': 'In ritardo',
    'revision.completed': 'Completate',
    'revision.addItem': 'Aggiungi elemento',
    'revision.noItems': 'Nessun elemento di revisione',
    'revision.markComplete': 'Segna come completato',
    'revision.postpone': 'Rimanda',
    'revision.edit': 'Modifica',
    'revision.delete': 'Elimina',
    
    // Settings
    'settings.title': 'Impostazioni',
    'settings.appearance': 'Aspetto',
    'settings.appearance.desc': 'Personalizza l\'aspetto dell\'applicazione',
    'settings.darkMode': 'Modalità scura',
    'settings.darkMode.desc': 'Abilita tema scuro',
    'settings.language': 'Lingua',
    'settings.language.placeholder': 'Seleziona lingua',
    
    'settings.notifications': 'Notifiche',
    'settings.notifications.desc': 'Configura come vuoi ricevere le notifiche',
    'settings.pushNotifications': 'Notifiche push',
    'settings.pushNotifications.desc': 'Ricevi notifiche nel browser',
    'settings.studyReminders': 'Promemoria di studio',
    'settings.studyReminders.desc': 'Ricevi promemoria per le tue sessioni di studio',
    
    'settings.pomodoro': 'Impostazioni Pomodoro',
    'settings.pomodoro.desc': 'Configura le impostazioni del tuo timer Pomodoro',
    'settings.focusTime': 'Tempo di concentrazione (min)',
    'settings.shortBreak': 'Pausa breve (min)',
    'settings.longBreak': 'Pausa lunga (min)',
    'settings.autoStartBreaks': 'Avvia automaticamente le pause',
    'settings.autoStartBreaks.desc': 'Avvia automaticamente le pause dopo ogni sessione',
    
    'settings.privacy': 'Privacy e sicurezza',
    'settings.privacy.desc': 'Configura le tue preferenze sulla privacy',
    'settings.autoBackup': 'Backup automatico',
    'settings.autoBackup.desc': 'Salva automaticamente i dati nel cloud',
    'settings.changePassword': 'Cambia password',
    
    'settings.resetData': 'Ripristina dati',
    'settings.resetData.desc': 'Ripristina o esporta i dati della tua app',
    'settings.exportData': 'Esporta dati',
    'settings.exportData.btn': 'Scarica dati JSON',
    'settings.resetSettings': 'Ripristina impostazioni',
    'settings.resetSettings.btn': 'Ripristina predefiniti',
    'settings.deleteAllData': 'Elimina tutti i dati',
    'settings.deleteAllData.btn': 'Elimina tutto permanentemente',
    
    'common.save': 'Salva modifiche',
    'common.cancel': 'Annulla',
    'common.back': 'Indietro',
    
    // Profile
    'profile.title': 'Profilo',
    'profile.personalInfo': 'Informazioni personali',
    'profile.personalInfo.desc': 'Configura le tue informazioni personali',
    'profile.firstName': 'Nome',
    'profile.firstName.placeholder': 'Il tuo nome',
    'profile.lastName': 'Cognome',
    'profile.lastName.placeholder': 'Il tuo cognome',
    'profile.email': 'Email',
    'profile.email.placeholder': 'tua@email.com',
    'profile.bio': 'Biografia',
    'profile.bio.placeholder': 'Raccontaci di te...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.calendar': 'التقويم',
    'nav.schedule': 'الجدول الزمني',
    'nav.revision': 'المراجعة',
    'nav.flashcards': 'البطاقات التعليمية',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.todayTasks': 'مهام اليوم',
    'dashboard.upcomingEvents': 'الأحداث القادمة',
    'dashboard.studyProgress': 'تقدم الدراسة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.addTask': 'إضافة مهمة',
    'dashboard.addEvent': 'إضافة حدث',
    'dashboard.startPomodoro': 'بدء بومودورو',
    'dashboard.noTasks': 'لا توجد مهام لليوم',
    'dashboard.noEvents': 'لا توجد أحداث قادمة',
    
    // Calendar
    'calendar.title': 'التقويم',
    'calendar.today': 'اليوم',
    'calendar.week': 'الأسبوع',
    'calendar.month': 'الشهر',
    'calendar.addEvent': 'إضافة حدث',
    'calendar.noEvents': 'لا توجد أحداث',
    'calendar.allDay': 'طوال اليوم',
    
    // Flashcards
    'flashcards.title': 'البطاقات التعليمية',
    'flashcards.myDecks': 'مجموعاتي',
    'flashcards.createDeck': 'إنشاء مجموعة',
    'flashcards.study': 'دراسة',
    'flashcards.cards': 'بطاقات',
    'flashcards.noDecks': 'لا توجد مجموعات تم إنشاؤها',
    'flashcards.createFirst': 'أنشئ مجموعتك الأولى للبدء',
    'flashcards.studyMode': 'وضع الدراسة',
    'flashcards.showAnswer': 'عرض الإجابة',
    'flashcards.nextCard': 'البطاقة التالية',
    'flashcards.difficulty.again': 'مرة أخرى',
    'flashcards.difficulty.hard': 'صعب',
    'flashcards.difficulty.good': 'جيد',
    'flashcards.difficulty.easy': 'سهل',
    
    // Revision
    'revision.title': 'المراجعة',
    'revision.today': 'اليوم',
    'revision.upcoming': 'القادمة',
    'revision.overdue': 'متأخرة',
    'revision.completed': 'مكتملة',
    'revision.addItem': 'إضافة عنصر',
    'revision.noItems': 'لا توجد عناصر مراجعة',
    'revision.markComplete': 'وضع علامة كمكتمل',
    'revision.postpone': 'تأجيل',
    'revision.edit': 'تعديل',
    'revision.delete': 'حذف',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.appearance': 'المظهر',
    'settings.appearance.desc': 'تخصيص مظهر التطبيق',
    'settings.darkMode': 'الوضع المظلم',
    'settings.darkMode.desc': 'تفعيل السمة المظلمة',
    'settings.language': 'اللغة',
    'settings.language.placeholder': 'اختر اللغة',
    
    'settings.notifications': 'الإشعارات',
    'settings.notifications.desc': 'تكوين كيفية تلقي الإشعارات',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.pushNotifications.desc': 'تلقي الإشعارات في المتصفح',
    'settings.studyReminders': 'تذكيرات الدراسة',
    'settings.studyReminders.desc': 'تلقي تذكيرات لجلسات الدراسة',
    
    'settings.pomodoro': 'إعدادات البومودورو',
    'settings.pomodoro.desc': 'تكوين إعدادات مؤقت البومودورو',
    'settings.focusTime': 'وقت التركيز (دقيقة)',
    'settings.shortBreak': 'استراحة قصيرة (دقيقة)',
    'settings.longBreak': 'استراحة طويلة (دقيقة)',
    'settings.autoStartBreaks': 'بدء الاستراحات تلقائياً',
    'settings.autoStartBreaks.desc': 'بدء الاستراحات تلقائياً بعد كل جلسة',
    
    'settings.privacy': 'الخصوصية والأمان',
    'settings.privacy.desc': 'تكوين تفضيلات الخصوصية',
    'settings.autoBackup': 'النسخ الاحتياطي التلقائي',
    'settings.autoBackup.desc': 'حفظ البيانات تلقائياً في السحابة',
    'settings.changePassword': 'تغيير كلمة المرور',
    
    'settings.resetData': 'إعادة تعيين البيانات',
    'settings.resetData.desc': 'إعادة تعيين أو تصدير بيانات التطبيق',
    'settings.exportData': 'تصدير البيانات',
    'settings.exportData.btn': 'تحميل بيانات JSON',
    'settings.resetSettings': 'إعادة تعيين الإعدادات',
    'settings.resetSettings.btn': 'استعادة الافتراضية',
    'settings.deleteAllData': 'حذف جميع البيانات',
    'settings.deleteAllData.btn': 'حذف كل شيء نهائياً',
    
    'common.save': 'حفظ التغييرات',
    'common.cancel': 'إلغاء',
    'common.back': 'رجوع',
    
    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.personalInfo.desc': 'تكوين معلوماتك الشخصية',
    'profile.firstName': 'الاسم الأول',
    'profile.firstName.placeholder': 'اسمك الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.lastName.placeholder': 'اسم عائلتك',
    'profile.email': 'البريد الإلكتروني',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'السيرة الذاتية',
    'profile.bio.placeholder': 'أخبرنا عن نفسك...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.calendar': 'कैलेंडर',
    'nav.schedule': 'अनुसूची',
    'nav.revision': 'संशोधन',
    'nav.flashcards': 'फ्लैशकार्ड',
    'nav.settings': 'सेटिंग्स',
    'nav.profile': 'प्रोफ़ाइल',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.todayTasks': 'आज के कार्य',
    'dashboard.upcomingEvents': 'आगामी घटनाएँ',
    'dashboard.studyProgress': 'अध्ययन प्रगति',
    'dashboard.quickActions': 'त्वरित क्रियाएँ',
    'dashboard.addTask': 'कार्य जोड़ें',
    'dashboard.addEvent': 'घटना जोड़ें',
    'dashboard.startPomodoro': 'पोमोडोरो शुरू करें',
    'dashboard.noTasks': 'आज कोई कार्य नहीं',
    'dashboard.noEvents': 'कोई आगामी घटनाएँ नहीं',
    
    // Calendar
    'calendar.title': 'कैलेंडर',
    'calendar.today': 'आज',
    'calendar.week': 'सप्ताह',
    'calendar.month': 'महीना',
    'calendar.addEvent': 'घटना जोड़ें',
    'calendar.noEvents': 'कोई घटना नहीं',
    'calendar.allDay': 'पूरा दिन',
    
    // Flashcards
    'flashcards.title': 'फ्लैशकार्ड',
    'flashcards.myDecks': 'मेरे डेक',
    'flashcards.createDeck': 'डेक बनाएं',
    'flashcards.study': 'अध्ययन करें',
    'flashcards.cards': 'कार्ड',
    'flashcards.noDecks': 'कोई डेक नहीं बनाया गया',
    'flashcards.createFirst': 'शुरू करने के लिए अपना पहला डेक बनाएं',
    'flashcards.studyMode': 'अध्ययन मोड',
    'flashcards.showAnswer': 'उत्तर दिखाएं',
    'flashcards.nextCard': 'अगला कार्ड',
    'flashcards.difficulty.again': 'फिर से',
    'flashcards.difficulty.hard': 'कठिन',
    'flashcards.difficulty.good': 'अच्छा',
    'flashcards.difficulty.easy': 'आसान',
    
    // Revision
    'revision.title': 'संशोधन',
    'revision.today': 'आज',
    'revision.upcoming': 'आगामी',
    'revision.overdue': 'मियाद समाप्त',
    'revision.completed': 'पूरा हुआ',
    'revision.addItem': 'आइटम जोड़ें',
    'revision.noItems': 'कोई संशोधन आइटम नहीं',
    'revision.markComplete': 'पूरा चिह्नित करें',
    'revision.postpone': 'स्थगित करें',
    'revision.edit': 'संपादित करें',
    'revision.delete': 'हटाएं',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.appearance': 'दिखावट',
    'settings.appearance.desc': 'ऐप की दिखावट को कस्टमाइज़ करें',
    'settings.darkMode': 'डार्क मोड',
    'settings.darkMode.desc': 'डार्क थीम सक्षम करें',
    'settings.language': 'भाषा',
    'settings.language.placeholder': 'भाषा चुनें',
    
    'settings.notifications': 'सूचनाएं',
    'settings.notifications.desc': 'सूचनाएं कैसे प्राप्त करना चाहते हैं, इसे कॉन्फ़िगर करें',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.pushNotifications.desc': 'ब्राउज़र में सूचनाएं प्राप्त करें',
    'settings.studyReminders': 'अध्ययन अनुस्मारक',
    'settings.studyReminders.desc': 'अपने अध्ययन सत्रों के लिए अनुस्मारक प्राप्त करें',
    
    'settings.pomodoro': 'पोमोडोरो सेटिंग्स',
    'settings.pomodoro.desc': 'अपने पोमोडोरो टाइमर सेटिंग्स कॉन्फ़िगर करें',
    'settings.focusTime': 'फोकस समय (मिनट)',
    'settings.shortBreak': 'छोटी ब्रेक (मिनट)',
    'settings.longBreak': 'लंबी ब्रेक (मिनट)',
    'settings.autoStartBreaks': 'स्वचालित ब्रेक शुरू करें',
    'settings.autoStartBreaks.desc': 'प्रत्येक सत्र के बाद ब्रेक स्वचालित रूप से शुरू करें',
    
    'settings.privacy': 'गोपनीयता और सुरक्षा',
    'settings.privacy.desc': 'अपनी गोपनीयता प्राथमिकताएं कॉन्फ़िगर करें',
    'settings.autoBackup': 'स्वचालित बैकअप',
    'settings.autoBackup.desc': 'डेटा को क्लाउड में स्वचालित रूप से सहेजें',
    'settings.changePassword': 'पासवर्ड बदलें',
    
    'settings.resetData': 'डेटा रीसेट करें',
    'settings.resetData.desc': 'अपने ऐप डेटा को रीसेट या निर्यात करें',
    'settings.exportData': 'डेटा निर्यात करें',
    'settings.exportData.btn': 'JSON डेटा डाउनलोड करें',
    'settings.resetSettings': 'सेटिंग्स रीसेट करें',
    'settings.resetSettings.btn': 'डिफ़ॉल्ट पुनर्स्थापित करें',
    'settings.deleteAllData': 'सभी डेटा हटाएं',
    'settings.deleteAllData.btn': 'सब कुछ स्थायी रूप से हटाएं',
    
    'common.save': 'परिवर्तन सहेजें',
    'common.cancel': 'रद्द करें',
    'common.back': 'वापस',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.personalInfo.desc': 'अपनी व्यक्तिगत जानकारी कॉन्फ़िगर करें',
    'profile.firstName': 'पहला नाम',
    'profile.firstName.placeholder': 'आपका पहला नाम',
    'profile.lastName': 'अंतिम नाम',
    'profile.lastName.placeholder': 'आपका अंतिम नाम',
    'profile.email': 'ईमेल',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'बायो',
    'profile.bio.placeholder': 'हमें अपने बारे में बताएं...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  bn: {
    // Navigation
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.calendar': 'ক্যালেন্ডার',
    'nav.schedule': 'সময়সূচী',
    'nav.revision': 'পুনর্বিবেচনা',
    'nav.flashcards': 'ফ্ল্যাশকার্ড',
    'nav.settings': 'সেটিংস',
    'nav.profile': 'প্রোফাইল',
    
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.todayTasks': 'আজকের কাজ',
    'dashboard.upcomingEvents': 'আসন্ন ইভেন্ট',
    'dashboard.studyProgress': 'অধ্যয়নের অগ্রগতি',
    'dashboard.quickActions': 'দ্রুত ক্রিয়াকলাপ',
    'dashboard.addTask': 'কাজ যোগ করুন',
    'dashboard.addEvent': 'ইভেন্ট যোগ করুন',
    'dashboard.startPomodoro': 'পোমোডোরো শুরু করুন',
    'dashboard.noTasks': 'আজ কোনও কাজ নেই',
    'dashboard.noEvents': 'কোনও আসন্ন ইভেন্ট নেই',
    
    // Calendar
    'calendar.title': 'ক্যালেন্ডার',
    'calendar.today': 'আজ',
    'calendar.week': 'সপ্তাহ',
    'calendar.month': 'মাস',
    'calendar.addEvent': 'ইভেন্ট যোগ করুন',
    'calendar.noEvents': 'কোনও ইভেন্ট নেই',
    'calendar.allDay': 'সারা দিন',
    
    // Flashcards
    'flashcards.title': 'ফ্ল্যাশকার্ড',
    'flashcards.myDecks': 'আমার ডেক',
    'flashcards.createDeck': 'ডেক তৈরি করুন',
    'flashcards.study': 'অধ্যয়ন করুন',
    'flashcards.cards': 'কার্ড',
    'flashcards.noDecks': 'কোনও ডেক তৈরি হয়নি',
    'flashcards.createFirst': 'শুরু করতে আপনার প্রথম ডেক তৈরি করুন',
    'flashcards.studyMode': 'অধ্যয়ন মোড',
    'flashcards.showAnswer': 'উত্তর দেখান',
    'flashcards.nextCard': 'পরবর্তী কার্ড',
    'flashcards.difficulty.again': 'আবার',
    'flashcards.difficulty.hard': 'কঠিন',
    'flashcards.difficulty.good': 'ভালো',
    'flashcards.difficulty.easy': 'সহজ',
    
    // Revision
    'revision.title': 'পুনর্বিবেচনা',
    'revision.today': 'আজ',
    'revision.upcoming': 'আসন্ন',
    'revision.overdue': 'বিলম্বিত',
    'revision.completed': 'সম্পন্ন',
    'revision.addItem': 'আইটেম যোগ করুন',
    'revision.noItems': 'কোনও পুনর্বিবেচনা আইটেম নেই',
    'revision.markComplete': 'সম্পন্ন হিসেবে চিহ্নিত করুন',
    'revision.postpone': 'স্থগিত করুন',
    'revision.edit': 'সম্পাদনা করুন',
    'revision.delete': 'মুছে ফেলুন',
    
    // Settings
    'settings.title': 'সেটিংস',
    'settings.appearance': 'দেখা',
    'settings.appearance.desc': 'অ্যাপের চেহারা কাস্টমাইজ করুন',
    'settings.darkMode': 'ডার্ক মোড',
    'settings.darkMode.desc': 'ডার্ক থিম সক্ষম করুন',
    'settings.language': 'ভাষা',
    'settings.language.placeholder': 'ভাষা নির্বাচন করুন',
    
    'settings.notifications': 'বিজ্ঞপ্তি',
    'settings.notifications.desc': 'আপনি কীভাবে বিজ্ঞপ্তি পেতে চান তা কনফিগার করুন',
    'settings.pushNotifications': 'পুশ বিজ্ঞপ্তি',
    'settings.pushNotifications.desc': 'ব্রাউজারে বিজ্ঞপ্তি গ্রহণ করুন',
    'settings.studyReminders': 'অধ্যয়ন অনুস্মারক',
    'settings.studyReminders.desc': 'আপনার অধ্যয়ন সেশনের জন্য অনুস্মারক গ্রহণ করুন',
    
    'settings.pomodoro': 'পোমোডোরো সেটিংস',
    'settings.pomodoro.desc': 'আপনার পোমোডোরো টাইমার সেটিংস কনফিগার করুন',
    'settings.focusTime': 'ফোকাস টাইম (মিনিট)',
    'settings.shortBreak': 'ছোট বিরতি (মিনিট)',
    'settings.longBreak': 'দীর্ঘ বিরতি (মিনিট)',
    'settings.autoStartBreaks': 'স্বয়ংক্রিয়ভাবে বিরতি শুরু করুন',
    'settings.autoStartBreaks.desc': 'প্রতিটি সেশনের পর স্বয়ংক্রিয়ভাবে বিরতি শুরু করুন',
    
    'settings.privacy': 'গোপনীয়তা এবং নিরাপত্তা',
    'settings.privacy.desc': 'আপনার গোপনীয়তার পছন্দগুলি কনফিগার করুন',
    'settings.autoBackup': 'স্বয়ংক্রিয় ব্যাকআপ',
    'settings.autoBackup.desc': 'ক্লাউডে স্বয়ংক্রিয়ভাবে ডেটা সংরক্ষণ করুন',
    'settings.changePassword': 'পাসওয়ার্ড পরিবর্তন করুন',
    
    'settings.resetData': 'ডেটা রিসেট করুন',
    'settings.resetData.desc': 'আপনার অ্যাপ ডেটা রিসেট বা এক্সপোর্ট করুন',
    'settings.exportData': 'ডেটা এক্সপোর্ট করুন',
    'settings.exportData.btn': 'JSON ডেটা ডাউনলোড করুন',
    'settings.resetSettings': 'সেটিংস রিসেট করুন',
    'settings.resetSettings.btn': 'ডিফল্ট পুনরুদ্ধার করুন',
    'settings.deleteAllData': 'সমস্ত ডেটা মুছে ফেলুন',
    'settings.deleteAllData.btn': 'সবকিছু স্থায়ীভাবে মুছে ফেলুন',
    
    'common.save': 'পরিবর্তন সংরক্ষণ করুন',
    'common.cancel': 'বাতিল',
    'common.back': 'ফিরে যান',
    
    // Profile
    'profile.title': 'প্রোফাইল',
    'profile.personalInfo': 'ব্যক্তিগত তথ্য',
    'profile.personalInfo.desc': 'আপনার ব্যক্তিগত তথ্য কনফিগার করুন',
    'profile.firstName': 'প্রথম নাম',
    'profile.firstName.placeholder': 'আপনার প্রথম নাম',
    'profile.lastName': 'শেষ নাম',
    'profile.lastName.placeholder': 'আপনার শেষ নাম',
    'profile.email': 'ইমেইল',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'বায়ো',
    'profile.bio.placeholder': 'আমাদের আপনার সম্পর্কে বলুন...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setStoredLanguage] = useLocalStorage<Language>('language', 'pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const setLanguage = (newLanguage: Language) => {
    setStoredLanguage(newLanguage);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
