import React, { createContext, useContext, ReactNode } from 'react';
import { useLocalStorage } from '../hooks/useLocalStorage';

type Language = 'pt' | 'en' | 'es' | 'zh' | 'ru' | 'fr' | 'it' | 'ar' | 'hi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// Traduções
const translations = {
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendário',
    'nav.schedule': 'Cronograma',
    'nav.revision': 'Revisão',
    'nav.flashcards': 'Flashcards',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Tarefas de Hoje',
    'dashboard.upcomingEvents': 'Próximos Eventos',
    'dashboard.studyProgress': 'Progresso dos Estudos',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.addTask': 'Adicionar Tarefa',
    'dashboard.addEvent': 'Adicionar Evento',
    'dashboard.startPomodoro': 'Iniciar Pomodoro',
    'dashboard.noTasks': 'Nenhuma tarefa para hoje',
    'dashboard.noEvents': 'Nenhum evento próximo',
    'dashboard.studySession': 'Sessão de Estudo',
    'dashboard.completedToday': 'Completadas Hoje',
    'dashboard.thisWeek': 'Esta Semana',
    'dashboard.pomodoroSessions': 'Sessões Pomodoro',
    'dashboard.totalTime': 'Tempo Total',
    'dashboard.averageSession': 'Sessão Média',
    'dashboard.studyStreak': 'Sequência de Estudos',
    'dashboard.reviewCards': 'Revisar Cartões',
    'dashboard.createFlashcard': 'Criar Flashcard',
    
    // Calendar
    'calendar.title': 'Calendário',
    'calendar.today': 'Hoje',
    'calendar.week': 'Semana',
    'calendar.month': 'Mês',
    'calendar.addEvent': 'Adicionar Evento',
    'calendar.noEvents': 'Nenhum evento',
    'calendar.allDay': 'Dia todo',
    'calendar.createEvent': 'Criar Evento',
    'calendar.editEvent': 'Editar Evento',
    'calendar.deleteEvent': 'Excluir Evento',
    'calendar.eventDetails': 'Detalhes do Evento',
    
    // Schedule
    'schedule.title': 'Cronograma',
    'schedule.addEvent': 'Adicionar Evento',
    'schedule.todaySchedule': 'Cronograma de Hoje',
    'schedule.weeklyView': 'Visualização Semanal',
    'schedule.monthlyView': 'Visualização Mensal',
    'schedule.noEvents': 'Nenhum evento programado',
    'schedule.createNewEvent': 'Criar Novo Evento',
    'schedule.eventTitle': 'Título do Evento',
    'schedule.eventDescription': 'Descrição do Evento',
    'schedule.eventDate': 'Data do Evento',
    'schedule.eventTime': 'Horário do Evento',
    'schedule.saveEvent': 'Salvar Evento',
    'schedule.editEvent': 'Editar Evento',
    'schedule.deleteEvent': 'Excluir Evento',
    'schedule.recurring': 'Recorrente',
    'schedule.priority': 'Prioridade',
    'schedule.low': 'Baixa',
    'schedule.medium': 'Média',
    'schedule.high': 'Alta',
    
    // Flashcards
    'flashcards.title': 'Flashcards',
    'flashcards.myDecks': 'Meus Baralhos',
    'flashcards.createDeck': 'Criar Baralho',
    'flashcards.study': 'Estudar',
    'flashcards.cards': 'cartas',
    'flashcards.noDecks': 'Nenhum baralho criado',
    'flashcards.createFirst': 'Crie seu primeiro baralho para começar',
    'flashcards.studyMode': 'Modo de Estudo',
    'flashcards.showAnswer': 'Mostrar Resposta',
    'flashcards.nextCard': 'Próxima Carta',
    'flashcards.difficulty.again': 'Novamente',
    'flashcards.difficulty.hard': 'Difícil',
    'flashcards.difficulty.good': 'Bom',
    'flashcards.difficulty.easy': 'Fácil',
    'flashcards.deckName': 'Nome do Baralho',
    'flashcards.deckDescription': 'Descrição do Baralho',
    'flashcards.addCard': 'Adicionar Carta',
    'flashcards.front': 'Frente',
    'flashcards.back': 'Verso',
    'flashcards.importDeck': 'Importar Baralho',
    'flashcards.exportDeck': 'Exportar Baralho',
    'flashcards.statistics': 'Estatísticas',
    'flashcards.masteredCards': 'Cartas Dominadas',
    'flashcards.learningCards': 'Cartas em Aprendizado',
    'flashcards.newCards': 'Cartas Novas',
    'flashcards.reviewCards': 'Cartas para Revisão',
    
    // Revision
    'revision.title': 'Revisão',
    'revision.today': 'Hoje',
    'revision.upcoming': 'Próximas',
    'revision.overdue': 'Atrasadas',
    'revision.completed': 'Concluídas',
    'revision.addItem': 'Adicionar Item',
    'revision.noItems': 'Nenhum item de revisão',
    'revision.markComplete': 'Marcar como Concluído',
    'revision.postpone': 'Adiar',
    'revision.edit': 'Editar',
    'revision.delete': 'Excluir',
    'revision.itemTitle': 'Título do Item',
    'revision.itemDescription': 'Descrição do Item',
    'revision.dueDate': 'Data de Vencimento',
    'revision.priority': 'Prioridade',
    'revision.subject': 'Matéria',
    'revision.createItem': 'Criar Item',
    'revision.editItem': 'Editar Item',
    'revision.deleteItem': 'Excluir Item',
    'revision.notes': 'Notas',
    'revision.studyTime': 'Tempo de Estudo',
    'revision.lastReviewed': 'Última Revisão',
    'revision.nextReview': 'Próxima Revisão',
    'revision.difficulty': 'Dificuldade',
    'revision.reviewInterval': 'Intervalo de Revisão',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.appearance': 'Aparência',
    'settings.appearance.desc': 'Personalize a aparência do aplicativo',
    'settings.darkMode': 'Modo Escuro',
    'settings.darkMode.desc': 'Ativar tema escuro',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Selecione o idioma',
    
    'settings.notifications': 'Notificações',
    'settings.notifications.desc': 'Configure como você quer receber notificações',
    'settings.pushNotifications': 'Notificações Push',
    'settings.pushNotifications.desc': 'Receba notificações no navegador',
    'settings.studyReminders': 'Lembretes de Estudo',
    'settings.studyReminders.desc': 'Receba lembretes para suas sessões de estudo',
    
    'settings.pomodoro': 'Configurações do Pomodoro',
    'settings.pomodoro.desc': 'Configure os tempos do seu timer Pomodoro',
    'settings.focusTime': 'Tempo de Foco (min)',
    'settings.shortBreak': 'Pausa Curta (min)',
    'settings.longBreak': 'Pausa Longa (min)',
    'settings.longBreakInterval': 'Intervalo Pausa Longa',
    'settings.autoStartBreaks': 'Iniciar Pausas Automaticamente',
    'settings.autoStartBreaks.desc': 'Iniciar pausas automaticamente após cada sessão',
    
    'settings.resetData': 'Redefinir Dados',
    'settings.resetData.desc': 'Redefina ou exporte seus dados do aplicativo',
    'settings.deleteSchedule': 'Apagar Cronograma',
    'settings.deleteSchedule.btn': 'Apagar Cronograma',
    'settings.deleteAllData': 'Apagar Todos os Dados',
    'settings.deleteAllData.btn': 'Apagar Tudo Permanentemente',
    'settings.scheduleDeleted': 'Cronograma apagado',
    'settings.scheduleDeleted.desc': 'Todos os eventos do cronograma foram removidos',
    'settings.allDataDeleted': 'Todos os dados apagados',
    'settings.allDataDeleted.desc': 'Todos os dados do aplicativo foram removidos permanentemente',
    'settings.changesSaved': 'Alterações salvas',
    'settings.changesSaved.desc': 'Suas configurações foram salvas com sucesso',
    
    'common.save': 'Salvar Alterações',
    'common.cancel': 'Cancelar',
    'common.back': 'Voltar',
    'common.add': 'Adicionar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.close': 'Fechar',
    'common.confirm': 'Confirmar',
    'common.create': 'Criar',
    'common.update': 'Atualizar',
    'common.remove': 'Remover',
    'common.view': 'Visualizar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.personalInfo.desc': 'Configure suas informações pessoais',
    'profile.firstName': 'Nome',
    'profile.firstName.placeholder': 'Seu nome',
    'profile.lastName': 'Sobrenome',
    'profile.lastName.placeholder': 'Seu sobrenome',
    'profile.email': 'Email',
    'profile.email.placeholder': 'seu@email.com',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Fale um pouco sobre você...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendar',
    'nav.schedule': 'Schedule',
    'nav.revision': 'Revision',
    'nav.flashcards': 'Flashcards',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Today\'s Tasks',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.studyProgress': 'Study Progress',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addTask': 'Add Task',
    'dashboard.addEvent': 'Add Event',
    'dashboard.startPomodoro': 'Start Pomodoro',
    'dashboard.noTasks': 'No tasks for today',
    'dashboard.noEvents': 'No upcoming events',
    'dashboard.studySession': 'Study Session',
    'dashboard.completedToday': 'Completed Today',
    'dashboard.thisWeek': 'This Week',
    'dashboard.pomodoroSessions': 'Pomodoro Sessions',
    'dashboard.totalTime': 'Total Time',
    'dashboard.averageSession': 'Average Session',
    'dashboard.studyStreak': 'Study Streak',
    'dashboard.reviewCards': 'Review Cards',
    'dashboard.createFlashcard': 'Create Flashcard',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.today': 'Today',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.addEvent': 'Add Event',
    'calendar.noEvents': 'No events',
    'calendar.allDay': 'All day',
    'calendar.createEvent': 'Create Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.deleteEvent': 'Delete Event',
    'calendar.eventDetails': 'Event Details',
    
    // Schedule
    'schedule.title': 'Schedule',
    'schedule.addEvent': 'Add Event',
    'schedule.todaySchedule': 'Today\'s Schedule',
    'schedule.weeklyView': 'Weekly View',
    'schedule.monthlyView': 'Monthly View',
    'schedule.noEvents': 'No scheduled events',
    'schedule.createNewEvent': 'Create New Event',
    'schedule.eventTitle': 'Event Title',
    'schedule.eventDescription': 'Event Description',
    'schedule.eventDate': 'Event Date',
    'schedule.eventTime': 'Event Time',
    'schedule.saveEvent': 'Save Event',
    'schedule.editEvent': 'Edit Event',
    'schedule.deleteEvent': 'Delete Event',
    'schedule.recurring': 'Recurring',
    'schedule.priority': 'Priority',
    'schedule.low': 'Low',
    'schedule.medium': 'Medium',
    'schedule.high': 'High',
    
    // Flashcards
    'flashcards.title': 'Flashcards',
    'flashcards.myDecks': 'My Decks',
    'flashcards.createDeck': 'Create Deck',
    'flashcards.study': 'Study',
    'flashcards.cards': 'cards',
    'flashcards.noDecks': 'No decks created',
    'flashcards.createFirst': 'Create your first deck to get started',
    'flashcards.studyMode': 'Study Mode',
    'flashcards.showAnswer': 'Show Answer',
    'flashcards.nextCard': 'Next Card',
    'flashcards.difficulty.again': 'Again',
    'flashcards.difficulty.hard': 'Hard',
    'flashcards.difficulty.good': 'Good',
    'flashcards.difficulty.easy': 'Easy',
    'flashcards.deckName': 'Deck Name',
    'flashcards.deckDescription': 'Deck Description',
    'flashcards.addCard': 'Add Card',
    'flashcards.front': 'Front',
    'flashcards.back': 'Back',
    'flashcards.importDeck': 'Import Deck',
    'flashcards.exportDeck': 'Export Deck',
    'flashcards.statistics': 'Statistics',
    'flashcards.masteredCards': 'Mastered Cards',
    'flashcards.learningCards': 'Learning Cards',
    'flashcards.newCards': 'New Cards',
    'flashcards.reviewCards': 'Review Cards',
    
    // Revision
    'revision.title': 'Revision',
    'revision.today': 'Today',
    'revision.upcoming': 'Upcoming',
    'revision.overdue': 'Overdue',
    'revision.completed': 'Completed',
    'revision.addItem': 'Add Item',
    'revision.noItems': 'No revision items',
    'revision.markComplete': 'Mark Complete',
    'revision.postpone': 'Postpone',
    'revision.edit': 'Edit',
    'revision.delete': 'Delete',
    'revision.itemTitle': 'Item Title',
    'revision.itemDescription': 'Item Description',
    'revision.dueDate': 'Due Date',
    'revision.priority': 'Priority',
    'revision.subject': 'Subject',
    'revision.createItem': 'Create Item',
    'revision.editItem': 'Edit Item',
    'revision.deleteItem': 'Delete Item',
    'revision.notes': 'Notes',
    'revision.studyTime': 'Study Time',
    'revision.lastReviewed': 'Last Reviewed',
    'revision.nextReview': 'Next Review',
    'revision.difficulty': 'Difficulty',
    'revision.reviewInterval': 'Review Interval',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Customize the app appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.darkMode.desc': 'Enable dark theme',
    'settings.language': 'Language',
    'settings.language.placeholder': 'Select language',
    
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Configure how you want to receive notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotifications.desc': 'Receive notifications in browser',
    'settings.studyReminders': 'Study Reminders',
    'settings.studyReminders.desc': 'Receive reminders for your study sessions',
    
    'settings.pomodoro': 'Pomodoro Settings',
    'settings.pomodoro.desc': 'Configure your Pomodoro timer settings',
    'settings.focusTime': 'Focus Time (min)',
    'settings.shortBreak': 'Short Break (min)',
    'settings.longBreak': 'Long Break (min)',
    'settings.longBreakInterval': 'Long Break Interval',
    'settings.autoStartBreaks': 'Auto Start Breaks',
    'settings.autoStartBreaks.desc': 'Automatically start breaks after each session',
    
    'settings.resetData': 'Reset Data',
    'settings.resetData.desc': 'Reset or export your app data',
    'settings.deleteSchedule': 'Delete Schedule',
    'settings.deleteSchedule.btn': 'Delete Schedule',
    'settings.deleteAllData': 'Delete All Data',
    'settings.deleteAllData.btn': 'Delete Everything Permanently',
    'settings.scheduleDeleted': 'Schedule deleted',
    'settings.scheduleDeleted.desc': 'All schedule events have been removed',
    'settings.allDataDeleted': 'All data deleted',
    'settings.allDataDeleted.desc': 'All app data has been permanently removed',
    'settings.changesSaved': 'Changes saved',
    'settings.changesSaved.desc': 'Your settings have been saved successfully',
    
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.remove': 'Remove',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfo.desc': 'Configure your personal information',
    'profile.firstName': 'First Name',
    'profile.firstName.placeholder': 'Your first name',
    'profile.lastName': 'Last Name',
    'profile.lastName.placeholder': 'Your last name',
    'profile.email': 'Email',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'Bio',
    'profile.bio.placeholder': 'Tell us about yourself...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendario',
    'nav.schedule': 'Horario',
    'nav.revision': 'Revisión',
    'nav.flashcards': 'Tarjetas',
    'nav.settings': 'Configuración',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Tareas de Hoy',
    'dashboard.upcomingEvents': 'Próximos Eventos',
    'dashboard.studyProgress': 'Progreso de Estudios',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.addTask': 'Agregar Tarea',
    'dashboard.addEvent': 'Agregar Evento',
    'dashboard.startPomodoro': 'Iniciar Pomodoro',
    'dashboard.noTasks': 'No hay tareas para hoy',
    'dashboard.noEvents': 'No hay eventos próximos',
    'dashboard.studySession': 'Sesión de Estudio',
    'dashboard.completedToday': 'Completadas Hoy',
    'dashboard.thisWeek': 'Esta Semana',
    'dashboard.pomodoroSessions': 'Sesiones Pomodoro',
    'dashboard.totalTime': 'Tiempo Total',
    'dashboard.averageSession': 'Sesión Promedio',
    'dashboard.studyStreak': 'Racha de Estudios',
    'dashboard.reviewCards': 'Revisar Tarjetas',
    'dashboard.createFlashcard': 'Crear Tarjeta',
    
    // Calendar
    'calendar.title': 'Calendario',
    'calendar.today': 'Hoy',
    'calendar.week': 'Semana',
    'calendar.month': 'Mes',
    'calendar.addEvent': 'Agregar Evento',
    'calendar.noEvents': 'No hay eventos',
    'calendar.allDay': 'Todo el día',
    'calendar.createEvent': 'Crear Evento',
    'calendar.editEvent': 'Editar Evento',
    'calendar.deleteEvent': 'Eliminar Evento',
    'calendar.eventDetails': 'Detalles del Evento',
    
    // Schedule
    'schedule.title': 'Horario',
    'schedule.addEvent': 'Agregar Evento',
    'schedule.todaySchedule': 'Horario de Hoy',
    'schedule.weeklyView': 'Vista Semanal',
    'schedule.monthlyView': 'Vista Mensual',
    'schedule.noEvents': 'No hay eventos programados',
    'schedule.createNewEvent': 'Crear Nuevo Evento',
    'schedule.eventTitle': 'Título del Evento',
    'schedule.eventDescription': 'Descripción del Evento',
    'schedule.eventDate': 'Fecha del Evento',
    'schedule.eventTime': 'Hora del Evento',
    'schedule.saveEvent': 'Guardar Evento',
    'schedule.editEvent': 'Editar Evento',
    'schedule.deleteEvent': 'Eliminar Evento',
    'schedule.recurring': 'Recurrente',
    'schedule.priority': 'Prioridad',
    'schedule.low': 'Baja',
    'schedule.medium': 'Media',
    'schedule.high': 'Alta',
    
    // Flashcards
    'flashcards.title': 'Tarjetas',
    'flashcards.myDecks': 'Mis Mazos',
    'flashcards.createDeck': 'Crear Mazo',
    'flashcards.study': 'Estudiar',
    'flashcards.cards': 'tarjetas',
    'flashcards.noDecks': 'No hay mazos creados',
    'flashcards.createFirst': 'Crea tu primer mazo para comenzar',
    'flashcards.studyMode': 'Modo de Estudio',
    'flashcards.showAnswer': 'Mostrar Respuesta',
    'flashcards.nextCard': 'Siguiente Tarjeta',
    'flashcards.difficulty.again': 'Otra vez',
    'flashcards.difficulty.hard': 'Difícil',
    'flashcards.difficulty.good': 'Bueno',
    'flashcards.difficulty.easy': 'Fácil',
    'flashcards.deckName': 'Nombre del Mazo',
    'flashcards.deckDescription': 'Descripción del Mazo',
    'flashcards.addCard': 'Agregar Tarjeta',
    'flashcards.front': 'Frente',
    'flashcards.back': 'Dorso',
    'flashcards.importDeck': 'Importar Mazo',
    'flashcards.exportDeck': 'Exportar Mazo',
    'flashcards.statistics': 'Estadísticas',
    'flashcards.masteredCards': 'Tarjetas Dominadas',
    'flashcards.learningCards': 'Tarjetas en Aprendizaje',
    'flashcards.newCards': 'Tarjetas Nuevas',
    'flashcards.reviewCards': 'Tarjetas para Revisar',
    
    // Revision
    'revision.title': 'Revisión',
    'revision.today': 'Hoy',
    'revision.upcoming': 'Próximas',
    'revision.overdue': 'Atrasadas',
    'revision.completed': 'Completadas',
    'revision.addItem': 'Agregar Elemento',
    'revision.noItems': 'No hay elementos de revisión',
    'revision.markComplete': 'Marcar como Completado',
    'revision.postpone': 'Posponer',
    'revision.edit': 'Editar',
    'revision.delete': 'Eliminar',
    'revision.itemTitle': 'Título del Elemento',
    'revision.itemDescription': 'Descripción del Elemento',
    'revision.dueDate': 'Fecha de Vencimiento',
    'revision.priority': 'Prioridad',
    'revision.subject': 'Materia',
    'revision.createItem': 'Crear Elemento',
    'revision.editItem': 'Editar Elemento',
    'revision.deleteItem': 'Eliminar Elemento',
    'revision.notes': 'Notas',
    'revision.studyTime': 'Tiempo de Estudio',
    'revision.lastReviewed': 'Última Revisión',
    'revision.nextReview': 'Próxima Revisión',
    'revision.difficulty': 'Dificultad',
    'revision.reviewInterval': 'Intervalo de Revisión',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.appearance': 'Apariencia',
    'settings.appearance.desc': 'Personaliza la apariencia de la aplicación',
    'settings.darkMode': 'Modo Oscuro',
    'settings.darkMode.desc': 'Activar tema oscuro',
    'settings.language': 'Idioma',
    'settings.language.placeholder': 'Seleccionar idioma',
    
    'settings.notifications': 'Notificaciones',
    'settings.notifications.desc': 'Configura cómo quieres recibir notificaciones',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.pushNotifications.desc': 'Recibir notificaciones en el navegador',
    'settings.studyReminders': 'Recordatorios de Estudio',
    'settings.studyReminders.desc': 'Recibir recordatorios para tus sesiones de estudio',
    
    'settings.pomodoro': 'Configuración de Pomodoro',
    'settings.pomodoro.desc': 'Configura los tiempos de tu temporizador Pomodoro',
    'settings.focusTime': 'Tiempo de Concentración (min)',
    'settings.shortBreak': 'Pausa Corta (min)',
    'settings.longBreak': 'Pausa Larga (min)',
    'settings.longBreakInterval': 'Intervalo Pausa Larga',
    'settings.autoStartBreaks': 'Iniciar Pausas Automáticamente',
    'settings.autoStartBreaks.desc': 'Iniciar pausas automáticamente después de cada sesión',
    
    'settings.resetData': 'Restablecer Datos',
    'settings.resetData.desc': 'Restablece o exporta los datos de tu aplicación',
    'settings.deleteSchedule': 'Eliminar Horario',
    'settings.deleteSchedule.btn': 'Eliminar Horario',
    'settings.deleteAllData': 'Eliminar Todos los Datos',
    'settings.deleteAllData.btn': 'Eliminar Todo Permanentemente',
    'settings.scheduleDeleted': 'Horario eliminado',
    'settings.scheduleDeleted.desc': 'Todos los eventos del horario han sido eliminados',
    'settings.allDataDeleted': 'Todos los datos eliminados',
    'settings.allDataDeleted.desc': 'Todos los datos de la aplicación han sido eliminados permanentemente',
    'settings.changesSaved': 'Cambios guardados',
    'settings.changesSaved.desc': 'Tus configuraciones han sido guardadas exitosamente',
    
    'common.save': 'Guardar Cambios',
    'common.cancel': 'Cancelar',
    'common.back': 'Volver',
    'common.add': 'Agregar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.remove': 'Remover',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.personalInfo': 'Información Personal',
    'profile.personalInfo.desc': 'Configura tu información personal',
    'profile.firstName': 'Nombre',
    'profile.firstName.placeholder': 'Tu nombre',
    'profile.lastName': 'Apellido',
    'profile.lastName.placeholder': 'Tu apellido',
    'profile.email': 'Email',
    'profile.email.placeholder': 'tu@email.com',
    'profile.bio': 'Biografía',
    'profile.bio.placeholder': 'Cuéntanos sobre ti...',
    
    // Languages
    'language.pt': 'Português',
    'language.en': 'English',
    'language.es': 'Español',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.calendar': '日历',
    'nav.schedule': '时间表',
    'nav.revision': '复习',
    'nav.flashcards': '抽认卡',
    'nav.settings': '设置',
    'nav.profile': '个人资料',
    
    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.todayTasks': '今日任务',
    'dashboard.upcomingEvents': '即将发生的事件',
    'dashboard.studyProgress': '学习进度',
    'dashboard.quickActions': '快速操作',
    'dashboard.addTask': '添加任务',
    'dashboard.addEvent': '添加事件',
    'dashboard.startPomodoro': '开始番茄钟',
    'dashboard.noTasks': '今日无任务',
    'dashboard.noEvents': '无即将发生的事件',
    'dashboard.studySession': '学习会话',
    'dashboard.completedToday': '今日完成',
    'dashboard.thisWeek': '本周',
    'dashboard.pomodoroSessions': '番茄钟会话',
    'dashboard.totalTime': '总时间',
    'dashboard.averageSession': '平均会话',
    'dashboard.studyStreak': '学习连胜',
    'dashboard.reviewCards': '复习卡片',
    'dashboard.createFlashcard': '创建抽认卡',
    
    // Calendar
    'calendar.title': '日历',
    'calendar.today': '今天',
    'calendar.week': '周',
    'calendar.month': '月',
    'calendar.addEvent': '添加事件',
    'calendar.noEvents': '无事件',
    'calendar.allDay': '全天',
    'calendar.createEvent': '创建事件',
    'calendar.editEvent': '编辑事件',
    'calendar.deleteEvent': '删除事件',
    'calendar.eventDetails': '事件详情',
    
    // Schedule
    'schedule.title': '时间表',
    'schedule.addEvent': '添加事件',
    'schedule.todaySchedule': '今日时间表',
    'schedule.weeklyView': '每周视图',
    'schedule.monthlyView': '每月视图',
    'schedule.noEvents': '无计划事件',
    'schedule.createNewEvent': '创建新事件',
    'schedule.eventTitle': '事件标题',
    'schedule.eventDescription': '事件描述',
    'schedule.eventDate': '事件日期',
    'schedule.eventTime': '事件时间',
    'schedule.saveEvent': '保存事件',
    'schedule.editEvent': '编辑事件',
    'schedule.deleteEvent': '删除事件',
    'schedule.recurring': '重复',
    'schedule.priority': '优先级',
    'schedule.low': '低',
    'schedule.medium': '中',
    'schedule.high': '高',
    
    // Flashcards
    'flashcards.title': '抽认卡',
    'flashcards.myDecks': '我的牌组',
    'flashcards.createDeck': '创建牌组',
    'flashcards.study': '学习',
    'flashcards.cards': '张牌',
    'flashcards.noDecks': '无已创建牌组',
    'flashcards.createFirst': '创建你的第一个牌组开始学习',
    'flashcards.studyMode': '学习模式',
    'flashcards.showAnswer': '显示答案',
    'flashcards.nextCard': '下一张牌',
    'flashcards.difficulty.again': '再来一次',
    'flashcards.difficulty.hard': '困难',
    'flashcards.difficulty.good': '好',
    'flashcards.difficulty.easy': '简单',
    'flashcards.deckName': '牌组名称',
    'flashcards.deckDescription': '牌组描述',
    'flashcards.addCard': '添加卡片',
    'flashcards.front': '正面',
    'flashcards.back': '背面',
    'flashcards.importDeck': '导入牌组',
    'flashcards.exportDeck': '导出牌组',
    'flashcards.statistics': '统计',
    'flashcards.masteredCards': '掌握的卡片',
    'flashcards.learningCards': '学习中的卡片',
    'flashcards.newCards': '新卡片',
    'flashcards.reviewCards': '复习卡片',
    
    // Revision
    'revision.title': '复习',
    'revision.today': '今天',
    'revision.upcoming': '即将到来',
    'revision.overdue': '逾期',
    'revision.completed': '已完成',
    'revision.addItem': '添加项目',
    'revision.noItems': '无复习项目',
    'revision.markComplete': '标记为完成',
    'revision.postpone': '推迟',
    'revision.edit': '编辑',
    'revision.delete': '删除',
    'revision.itemTitle': '项目标题',
    'revision.itemDescription': '项目描述',
    'revision.dueDate': '截止日期',
    'revision.priority': '优先级',
    'revision.subject': '科目',
    'revision.createItem': '创建项目',
    'revision.editItem': '编辑项目',
    'revision.deleteItem': '删除项目',
    'revision.notes': '笔记',
    'revision.studyTime': '学习时间',
    'revision.lastReviewed': '上次复习',
    'revision.nextReview': '下次复习',
    'revision.difficulty': '难度',
    'revision.reviewInterval': '复习间隔',
    
    // Settings
    'settings.title': '设置',
    'settings.appearance': '外观',
    'settings.appearance.desc': '自定义应用程序外观',
    'settings.darkMode': '深色模式',
    'settings.darkMode.desc': '启用深色主题',
    'settings.language': '语言',
    'settings.language.placeholder': '选择语言',
    
    'settings.notifications': '通知',
    'settings.notifications.desc': '配置您想要接收通知的方式',
    'settings.pushNotifications': '推送通知',
    'settings.pushNotifications.desc': '在浏览器中接收通知',
    'settings.studyReminders': '学习提醒',
    'settings.studyReminders.desc': '接收学习会话提醒',
    
    'settings.pomodoro': '番茄工作法设置',
    'settings.pomodoro.desc': '配置您的番茄工作法计时器设置',
    'settings.focusTime': '专注时间（分钟）',
    'settings.shortBreak': '短暂休息（分钟）',
    'settings.longBreak': '长时间休息（分钟）',
    'settings.longBreakInterval': '长休息间隔',
    'settings.autoStartBreaks': '自动开始休息',
    'settings.autoStartBreaks.desc': '每次会话后自动开始休息',
    
    'settings.resetData': '重置数据',
    'settings.resetData.desc': '重置或导出您的应用数据',
    'settings.deleteSchedule': '删除时间表',
    'settings.deleteSchedule.btn': '删除时间表',
    'settings.deleteAllData': '删除所有数据',
    'settings.deleteAllData.btn': '永久删除所有内容',
    'settings.scheduleDeleted': '时间表已删除',
    'settings.scheduleDeleted.desc': '所有时间表事件已被移除',
    'settings.allDataDeleted': '所有数据已删除',
    'settings.allDataDeleted.desc': '所有应用数据已被永久删除',
    
    'common.save': '保存更改',
    'common.cancel': '取消',
    'common.back': '返回',
    
    // Profile
    'profile.title': '个人资料',
    'profile.personalInfo': '个人信息',
    'profile.personalInfo.desc': '配置您的个人信息',
    'profile.firstName': '名字',
    'profile.firstName.placeholder': '您的名字',
    'profile.lastName': '姓氏',
    'profile.lastName.placeholder': '您的姓氏',
    'profile.email': '电子邮件',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': '简介',
    'profile.bio.placeholder': '告诉我们您的情况...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель управления',
    'nav.calendar': 'Календарь',
    'nav.schedule': 'Расписание',
    'nav.revision': 'Повторение',
    'nav.flashcards': 'Флэш-карты',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    
    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.todayTasks': 'Задачи на сегодня',
    'dashboard.upcomingEvents': 'Предстоящие события',
    'dashboard.studyProgress': 'Прогресс обучения',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.addTask': 'Добавить задачу',
    'dashboard.addEvent': 'Добавить событие',
    'dashboard.startPomodoro': 'Начать Помодоро',
    'dashboard.noTasks': 'Нет задач на сегодня',
    'dashboard.noEvents': 'Нет предстоящих событий',
    'dashboard.studySession': 'Сессия обучения',
    'dashboard.completedToday': 'Выполнено сегодня',
    'dashboard.thisWeek': 'На этой неделе',
    'dashboard.pomodoroSessions': 'Сессии Помодоро',
    'dashboard.totalTime': 'Общее время',
    'dashboard.averageSession': 'Средняя сессия',
    'dashboard.studyStreak': 'Серия обучения',
    'dashboard.reviewCards': 'Повторить карты',
    'dashboard.createFlashcard': 'Создать флэш-карту',
    
    // Calendar
    'calendar.title': 'Календарь',
    'calendar.today': 'Сегодня',
    'calendar.week': 'Неделя',
    'calendar.month': 'Месяц',
    'calendar.addEvent': 'Добавить событие',
    'calendar.noEvents': 'Нет событий',
    'calendar.allDay': 'Весь день',
    'calendar.createEvent': 'Создать событие',
    'calendar.editEvent': 'Редактировать событие',
    'calendar.deleteEvent': 'Удалить событие',
    'calendar.eventDetails': 'Детали события',
    
    // Schedule
    'schedule.title': 'Расписание',
    'schedule.addEvent': 'Добавить событие',
    'schedule.todaySchedule': 'Расписание на сегодня',
    'schedule.weeklyView': 'Еженедельный просмотр',
    'schedule.monthlyView': 'Ежемесячный просмотр',
    'schedule.noEvents': 'Нет запланированных событий',
    'schedule.createNewEvent': 'Создать новое событие',
    'schedule.eventTitle': 'Название события',
    'schedule.eventDescription': 'Описание события',
    'schedule.eventDate': 'Дата события',
    'schedule.eventTime': 'Время события',
    'schedule.saveEvent': 'Сохранить событие',
    'schedule.editEvent': 'Редактировать событие',
    'schedule.deleteEvent': 'Удалить событие',
    'schedule.recurring': 'Повторяющееся',
    'schedule.priority': 'Приоритет',
    'schedule.low': 'Низкий',
    'schedule.medium': 'Средний',
    'schedule.high': 'Высокий',
    
    // Flashcards
    'flashcards.title': 'Флэш-карты',
    'flashcards.myDecks': 'Мои колоды',
    'flashcards.createDeck': 'Создать колоду',
    'flashcards.study': 'Учить',
    'flashcards.cards': 'карты',
    'flashcards.noDecks': 'Колоды не созданы',
    'flashcards.createFirst': 'Создайте первую колоду, чтобы начать',
    'flashcards.studyMode': 'Режим обучения',
    'flashcards.showAnswer': 'Показать ответ',
    'flashcards.nextCard': 'Следующая карта',
    'flashcards.difficulty.again': 'Снова',
    'flashcards.difficulty.hard': 'Сложно',
    'flashcards.difficulty.good': 'Хорошо',
    'flashcards.difficulty.easy': 'Легко',
    'flashcards.deckName': 'Название колоды',
    'flashcards.deckDescription': 'Описание колоды',
    'flashcards.addCard': 'Добавить карту',
    'flashcards.front': 'Лицевая сторона',
    'flashcards.back': 'Обратная сторона',
    'flashcards.importDeck': 'Импортировать колоду',
    'flashcards.exportDeck': 'Экспортировать колоду',
    'flashcards.statistics': 'Статистика',
    'flashcards.masteredCards': 'Освоенные карты',
    'flashcards.learningCards': 'Изучаемые карты',
    'flashcards.newCards': 'Новые карты',
    'flashcards.reviewCards': 'Карты для повторения',
    
    // Revision
    'revision.title': 'Повторение',
    'revision.today': 'Сегодня',
    'revision.upcoming': 'Предстоящие',
    'revision.overdue': 'Просроченные',
    'revision.completed': 'Завершённые',
    'revision.addItem': 'Добавить элемент',
    'revision.noItems': 'Нет элементов для повторения',
    'revision.markComplete': 'Отметить как выполненное',
    'revision.postpone': 'Отложить',
    'revision.edit': 'Редактировать',
    'revision.delete': 'Удалить',
    'revision.itemTitle': 'Название элемента',
    'revision.itemDescription': 'Описание элемента',
    'revision.dueDate': 'Срок выполнения',
    'revision.priority': 'Приоритет',
    'revision.subject': 'Предмет',
    'revision.createItem': 'Создать элемент',
    'revision.editItem': 'Редактировать элемент',
    'revision.deleteItem': 'Удалить элемент',
    'revision.notes': 'Заметки',
    'revision.studyTime': 'Время обучения',
    'revision.lastReviewed': 'Последнее повторение',
    'revision.nextReview': 'Следующее повторение',
    'revision.difficulty': 'Сложность',
    'revision.reviewInterval': 'Интервал повторения',
    
    // Settings
    'settings.title': 'Настройки',
    'settings.appearance': 'Внешний вид',
    'settings.appearance.desc': 'Настройте внешний вид приложения',
    'settings.darkMode': 'Тёмная тема',
    'settings.darkMode.desc': 'Включить тёмную тему',
    'settings.language': 'Язык',
    'settings.language.placeholder': 'Выберите язык',
    
    'settings.notifications': 'Уведомления',
    'settings.notifications.desc': 'Настройте способ получения уведомлений',
    'settings.pushNotifications': 'Push-уведомления',
    'settings.pushNotifications.desc': 'Получать уведомления в браузере',
    'settings.studyReminders': 'Напоминания об учебе',
    'settings.studyReminders.desc': 'Получать напоминания о ваших учебных сессиях',
    
    'settings.pomodoro': 'Настройки Помодоро',
    'settings.pomodoro.desc': 'Настройте параметры таймера Помодоро',
    'settings.focusTime': 'Время концентрации (мин)',
    'settings.shortBreak': 'Короткий перерыв (мин)',
    'settings.longBreak': 'Длинный перерыв (мин)',
    'settings.longBreakInterval': 'Интервал длинного перерыва',
    'settings.autoStartBreaks': 'Автоматически начинать перерывы',
    'settings.autoStartBreaks.desc': 'Автоматически начинать перерывы после каждой сессии',
    
    'settings.resetData': 'Сброс данных',
    'settings.resetData.desc': 'Сбросить или экспортировать данные приложения',
    'settings.deleteSchedule': 'Удалить расписание',
    'settings.deleteSchedule.btn': 'Удалить расписание',
    'settings.deleteAllData': 'Удалить все данные',
    'settings.deleteAllData.btn': 'Удалить все навсегда',
    'settings.scheduleDeleted': 'Расписание удалено',
    'settings.scheduleDeleted.desc': 'Все события расписания были удалены',
    'settings.allDataDeleted': 'Все данные удалены',
    'settings.allDataDeleted.desc': 'Все данные приложения были удалены навсегда',
    
    'common.save': 'Сохранить изменения',
    'common.cancel': 'Отмена',
    'common.back': 'Назад',
    
    // Profile
    'profile.title': 'Профиль',
    'profile.personalInfo': 'Личная информация',
    'profile.personalInfo.desc': 'Настройте вашу личную информацию',
    'profile.firstName': 'Имя',
    'profile.firstName.placeholder': 'Ваше имя',
    'profile.lastName': 'Фамилия',
    'profile.lastName.placeholder': 'Ваша фамилия',
    'profile.email': 'Электронная почта',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'Биография',
    'profile.bio.placeholder': 'Расскажите нам о себе...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.calendar': 'Calendrier',
    'nav.schedule': 'Horaire',
    'nav.revision': 'Révision',
    'nav.flashcards': 'Cartes mémoire',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.todayTasks': 'Tâches du jour',
    'dashboard.upcomingEvents': 'Événements à venir',
    'dashboard.studyProgress': 'Progression des études',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.addTask': 'Ajouter une tâche',
    'dashboard.addEvent': 'Ajouter un événement',
    'dashboard.startPomodoro': 'Démarrer Pomodoro',
    'dashboard.noTasks': 'Aucune tâche pour aujourd\'hui',
    'dashboard.noEvents': 'Aucun événement à venir',
    'dashboard.studySession': 'Session d\'étude',
    'dashboard.completedToday': 'Terminées aujourd\'hui',
    'dashboard.thisWeek': 'Cette semaine',
    'dashboard.pomodoroSessions': 'Sessions Pomodoro',
    'dashboard.totalTime': 'Temps total',
    'dashboard.averageSession': 'Session moyenne',
    'dashboard.studyStreak': 'Série d\'études',
    'dashboard.reviewCards': 'Réviser les cartes',
    'dashboard.createFlashcard': 'Créer une carte mémoire',
    
    // Calendar
    'calendar.title': 'Calendrier',
    'calendar.today': 'Aujourd\'hui',
    'calendar.week': 'Semaine',
    'calendar.month': 'Mois',
    'calendar.addEvent': 'Ajouter un événement',
    'calendar.noEvents': 'Aucun événement',
    'calendar.allDay': 'Toute la journée',
    'calendar.createEvent': 'Créer un événement',
    'calendar.editEvent': 'Modifier un événement',
    'calendar.deleteEvent': 'Supprimer un événement',
    'calendar.eventDetails': 'Détails de l\'événement',
    
    // Schedule
    'schedule.title': 'Horaire',
    'schedule.addEvent': 'Ajouter un événement',
    'schedule.todaySchedule': 'Horaire d\'aujourd\'hui',
    'schedule.weeklyView': 'Vue hebdomadaire',
    'schedule.monthlyView': 'Vue mensuelle',
    'schedule.noEvents': 'Aucun événement programmé',
    'schedule.createNewEvent': 'Créer un nouvel événement',
    'schedule.eventTitle': 'Titre de l\'événement',
    'schedule.eventDescription': 'Description de l\'événement',
    'schedule.eventDate': 'Date de l\'événement',
    'schedule.eventTime': 'Heure de l\'événement',
    'schedule.saveEvent': 'Enregistrer l\'événement',
    'schedule.editEvent': 'Modifier l\'événement',
    'schedule.deleteEvent': 'Supprimer l\'événement',
    'schedule.recurring': 'Récurrent',
    'schedule.priority': 'Priorité',
    'schedule.low': 'Faible',
    'schedule.medium': 'Moyenne',
    'schedule.high': 'Élevée',
    
    // Flashcards
    'flashcards.title': 'Cartes mémoire',
    'flashcards.myDecks': 'Mes jeux',
    'flashcards.createDeck': 'Créer un jeu',
    'flashcards.study': 'Étudier',
    'flashcards.cards': 'cartes',
    'flashcards.noDecks': 'Aucun jeu créé',
    'flashcards.createFirst': 'Créez votre premier jeu pour commencer',
    'flashcards.studyMode': 'Mode d\'étude',
    'flashcards.showAnswer': 'Afficher la réponse',
    'flashcards.nextCard': 'Carte suivante',
    'flashcards.difficulty.again': 'Encore',
    'flashcards.difficulty.hard': 'Difficile',
    'flashcards.difficulty.good': 'Bien',
    'flashcards.difficulty.easy': 'Facile',
    'flashcards.deckName': 'Nom du jeu',
    'flashcards.deckDescription': 'Description du jeu',
    'flashcards.addCard': 'Ajouter une carte',
    'flashcards.front': 'Recto',
    'flashcards.back': 'Verso',
    'flashcards.importDeck': 'Importer un jeu',
    'flashcards.exportDeck': 'Exporter un jeu',
    'flashcards.statistics': 'Statistiques',
    'flashcards.masteredCards': 'Cartes maîtrisées',
    'flashcards.learningCards': 'Cartes en apprentissage',
    'flashcards.newCards': 'Nouvelles cartes',
    'flashcards.reviewCards': 'Cartes à réviser',
    
    // Revision
    'revision.title': 'Révision',
    'revision.today': 'Aujourd\'hui',
    'revision.upcoming': 'À venir',
    'revision.overdue': 'En retard',
    'revision.completed': 'Terminées',
    'revision.addItem': 'Ajouter un élément',
    'revision.noItems': 'Aucun élément de révision',
    'revision.markComplete': 'Marquer comme terminé',
    'revision.postpone': 'Reporter',
    'revision.edit': 'Modifier',
    'revision.delete': 'Supprimer',
    'revision.itemTitle': 'Titre de l\'élément',
    'revision.itemDescription': 'Description de l\'élément',
    'revision.dueDate': 'Date d\'échéance',
    'revision.priority': 'Priorité',
    'revision.subject': 'Sujet',
    'revision.createItem': 'Créer un élément',
    'revision.editItem': 'Modifier un élément',
    'revision.deleteItem': 'Supprimer un élément',
    'revision.notes': 'Notes',
    'revision.studyTime': 'Temps d\'étude',
    'revision.lastReviewed': 'Dernière révision',
    'revision.nextReview': 'Prochaine révision',
    'revision.difficulty': 'Difficulté',
    'revision.reviewInterval': 'Intervalle de révision',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.appearance': 'Apparence',
    'settings.appearance.desc': 'Personnalisez l\'apparence de l\'application',
    'settings.darkMode': 'Mode sombre',
    'settings.darkMode.desc': 'Activer le thème sombre',
    'settings.language': 'Langue',
    'settings.language.placeholder': 'Sélectionner la langue',
    
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Configurez la façon dont vous souhaitez recevoir les notifications',
    'settings.pushNotifications': 'Notifications push',
    'settings.pushNotifications.desc': 'Recevoir des notifications dans le navigateur',
    'settings.studyReminders': 'Rappels d\'étude',
    'settings.studyReminders.desc': 'Recevoir des rappels pour vos sessions d\'étude',
    
    'settings.pomodoro': 'Paramètres Pomodoro',
    'settings.pomodoro.desc': 'Configurez les paramètres de votre minuteur Pomodoro',
    'settings.focusTime': 'Temps de concentration (min)',
    'settings.shortBreak': 'Pause courte (min)',
    'settings.longBreak': 'Pause longue (min)',
    'settings.longBreakInterval': 'Intervalle pause longue',
    'settings.autoStartBreaks': 'Démarrer automatiquement les pauses',
    'settings.autoStartBreaks.desc': 'Démarrer automatiquement les pauses après chaque session',
    
    'settings.resetData': 'Réinitialiser les données',
    'settings.resetData.desc': 'Réinitialisez ou exportez les données de votre application',
    'settings.deleteSchedule': 'Supprimer l\'horaire',
    'settings.deleteSchedule.btn': 'Supprimer l\'horaire',
    'settings.deleteAllData': 'Supprimer toutes les données',
    'settings.deleteAllData.btn': 'Tout supprimer définitivement',
    'settings.scheduleDeleted': 'Horaire supprimé',
    'settings.scheduleDeleted.desc': 'Tous les événements de l\'horaire ont été supprimés',
    'settings.allDataDeleted': 'Toutes les données supprimées',
    'settings.allDataDeleted.desc': 'Toutes les données de l\'application ont été supprimées définitivement',
    
    'common.save': 'Enregistrer les modifications',
    'common.cancel': 'Annuler',
    'common.back': 'Retour',
    
    // Profile
    'profile.title': 'Profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.personalInfo.desc': 'Configurez vos informations personnelles',
    'profile.firstName': 'Prénom',
    'profile.firstName.placeholder': 'Votre prénom',
    'profile.lastName': 'Nom de famille',
    'profile.lastName.placeholder': 'Votre nom de famille',
    'profile.email': 'E-mail',
    'profile.email.placeholder': 'votre@email.com',
    'profile.bio': 'Biographie',
    'profile.bio.placeholder': 'Parlez-nous de vous...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  it: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendario',
    'nav.schedule': 'Orario',
    'nav.revision': 'Revisione',
    'nav.flashcards': 'Flashcard',
    'nav.settings': 'Impostazioni',
    'nav.profile': 'Profilo',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayTasks': 'Compiti di oggi',
    'dashboard.upcomingEvents': 'Eventi imminenti',
    'dashboard.studyProgress': 'Progresso dello studio',
    'dashboard.quickActions': 'Azioni rapide',
    'dashboard.addTask': 'Aggiungi compito',
    'dashboard.addEvent': 'Aggiungi evento',
    'dashboard.startPomodoro': 'Avvia Pomodoro',
    'dashboard.noTasks': 'Nessun compito per oggi',
    'dashboard.noEvents': 'Nessun evento imminente',
    'dashboard.studySession': 'Sessione di studio',
    'dashboard.completedToday': 'Completati oggi',
    'dashboard.thisWeek': 'Questa settimana',
    'dashboard.pomodoroSessions': 'Sessioni Pomodoro',
    'dashboard.totalTime': 'Tempo totale',
    'dashboard.averageSession': 'Sessione media',
    'dashboard.studyStreak': 'Serie di studio',
    'dashboard.reviewCards': 'Rivedi le carte',
    'dashboard.createFlashcard': 'Crea Flashcard',
    
    // Calendar
    'calendar.title': 'Calendario',
    'calendar.today': 'Oggi',
    'calendar.week': 'Settimana',
    'calendar.month': 'Mese',
    'calendar.addEvent': 'Aggiungi evento',
    'calendar.noEvents': 'Nessun evento',
    'calendar.allDay': 'Tutto il giorno',
    'calendar.createEvent': 'Crea evento',
    'calendar.editEvent': 'Modifica evento',
    'calendar.deleteEvent': 'Elimina evento',
    'calendar.eventDetails': 'Dettagli evento',
    
    // Schedule
    'schedule.title': 'Orario',
    'schedule.addEvent': 'Aggiungi evento',
    'schedule.todaySchedule': 'Orario di oggi',
    'schedule.weeklyView': 'Vista settimanale',
    'schedule.monthlyView': 'Vista mensile',
    'schedule.noEvents': 'Nessun evento programmato',
    'schedule.createNewEvent': 'Crea nuovo evento',
    'schedule.eventTitle': 'Titolo evento',
    'schedule.eventDescription': 'Descrizione evento',
    'schedule.eventDate': 'Data evento',
    'schedule.eventTime': 'Orario evento',
    'schedule.saveEvent': 'Salva evento',
    'schedule.editEvent': 'Modifica evento',
    'schedule.deleteEvent': 'Elimina evento',
    'schedule.recurring': 'Ricorrente',
    'schedule.priority': 'Priorità',
    'schedule.low': 'Bassa',
    'schedule.medium': 'Media',
    'schedule.high': 'Alta',
    
    // Flashcards
    'flashcards.title': 'Flashcard',
    'flashcards.myDecks': 'I miei mazzi',
    'flashcards.createDeck': 'Crea mazzo',
    'flashcards.study': 'Studia',
    'flashcards.cards': 'carte',
    'flashcards.noDecks': 'Nessun mazzo creato',
    'flashcards.createFirst': 'Crea il tuo primo mazzo per iniziare',
    'flashcards.studyMode': 'Modalità di studio',
    'flashcards.showAnswer': 'Mostra risposta',
    'flashcards.nextCard': 'Carta successiva',
    'flashcards.difficulty.again': 'Ancora',
    'flashcards.difficulty.hard': 'Difficile',
    'flashcards.difficulty.good': 'Buono',
    'flashcards.difficulty.easy': 'Facile',
    'flashcards.deckName': 'Nome mazzo',
    'flashcards.deckDescription': 'Descrizione mazzo',
    'flashcards.addCard': 'Aggiungi carta',
    'flashcards.front': 'Fronte',
    'flashcards.back': 'Retro',
    'flashcards.importDeck': 'Importa mazzo',
    'flashcards.exportDeck': 'Esporta mazzo',
    'flashcards.statistics': 'Statistiche',
    'flashcards.masteredCards': 'Carte padroneggiate',
    'flashcards.learningCards': 'Carte in apprendimento',
    'flashcards.newCards': 'Carte nuove',
    'flashcards.reviewCards': 'Carte da rivedere',
    
    // Revision
    'revision.title': 'Revisione',
    'revision.today': 'Oggi',
    'revision.upcoming': 'Imminenti',
    'revision.overdue': 'In ritardo',
    'revision.completed': 'Completate',
    'revision.addItem': 'Aggiungi elemento',
    'revision.noItems': 'Nessun elemento di revisione',
    'revision.markComplete': 'Segna come completato',
    'revision.postpone': 'Rimanda',
    'revision.edit': 'Modifica',
    'revision.delete': 'Elimina',
    'revision.itemTitle': 'Titolo elemento',
    'revision.itemDescription': 'Descrizione elemento',
    'revision.dueDate': 'Data scadenza',
    'revision.priority': 'Priorità',
    'revision.subject': 'Materia',
    'revision.createItem': 'Crea elemento',
    'revision.editItem': 'Modifica elemento',
    'revision.deleteItem': 'Elimina elemento',
    'revision.notes': 'Note',
    'revision.studyTime': 'Tempo di studio',
    'revision.lastReviewed': 'Ultima revisione',
    'revision.nextReview': 'Prossima revisione',
    'revision.difficulty': 'Difficoltà',
    'revision.reviewInterval': 'Intervallo revisione',
    
    // Settings
    'settings.title': 'Impostazioni',
    'settings.appearance': 'Aspetto',
    'settings.appearance.desc': 'Personalizza l\'aspetto dell\'applicazione',
    'settings.darkMode': 'Modalità scura',
    'settings.darkMode.desc': 'Abilita tema scuro',
    'settings.language': 'Lingua',
    'settings.language.placeholder': 'Seleziona lingua',
    
    'settings.notifications': 'Notifiche',
    'settings.notifications.desc': 'Configura come vuoi ricevere le notifiche',
    'settings.pushNotifications': 'Notifiche push',
    'settings.pushNotifications.desc': 'Ricevi notifiche nel browser',
    'settings.studyReminders': 'Promemoria di studio',
    'settings.studyReminders.desc': 'Ricevi promemoria per le tue sessioni di studio',
    
    'settings.pomodoro': 'Impostazioni Pomodoro',
    'settings.pomodoro.desc': 'Configura le impostazioni del tuo timer Pomodoro',
    'settings.focusTime': 'Tempo di concentrazione (min)',
    'settings.shortBreak': 'Pausa breve (min)',
    'settings.longBreak': 'Pausa lunga (min)',
    'settings.longBreakInterval': 'Intervallo pausa lunga',
    'settings.autoStartBreaks': 'Avvia automaticamente le pause',
    'settings.autoStartBreaks.desc': 'Avvia automaticamente le pause dopo ogni sessione',
    
    'settings.resetData': 'Ripristina dati',
    'settings.resetData.desc': 'Ripristina o esporta i dati della tua app',
    'settings.deleteSchedule': 'Elimina orario',
    'settings.deleteSchedule.btn': 'Elimina orario',
    'settings.deleteAllData': 'Elimina tutti i dati',
    'settings.deleteAllData.btn': 'Elimina tutto permanentemente',
    'settings.scheduleDeleted': 'Orario eliminato',
    'settings.scheduleDeleted.desc': 'Tutti gli eventi dell\'orario sono stati rimossi',
    'settings.allDataDeleted': 'Tutti i dati eliminati',
    'settings.allDataDeleted.desc': 'Tutti i dati dell\'app sono stati eliminati permanentemente',
    
    'common.save': 'Salva modifiche',
    'common.cancel': 'Annulla',
    'common.back': 'Indietro',
    
    // Profile
    'profile.title': 'Profilo',
    'profile.personalInfo': 'Informazioni personali',
    'profile.personalInfo.desc': 'Configura le tue informazioni personali',
    'profile.firstName': 'Nome',
    'profile.firstName.placeholder': 'Il tuo nome',
    'profile.lastName': 'Cognome',
    'profile.lastName.placeholder': 'Il tuo cognome',
    'profile.email': 'Email',
    'profile.email.placeholder': 'tua@email.com',
    'profile.bio': 'Biografia',
    'profile.bio.placeholder': 'Raccontaci di te...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.calendar': 'التقويم',
    'nav.schedule': 'الجدول الزمني',
    'nav.revision': 'المراجعة',
    'nav.flashcards': 'البطاقات التعليمية',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.todayTasks': 'مهام اليوم',
    'dashboard.upcomingEvents': 'الأحداث القادمة',
    'dashboard.studyProgress': 'تقدم الدراسة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.addTask': 'إضافة مهمة',
    'dashboard.addEvent': 'إضافة حدث',
    'dashboard.startPomodoro': 'بدء بومودورو',
    'dashboard.noTasks': 'لا توجد مهام لليوم',
    'dashboard.noEvents': 'لا توجد أحداث قادمة',
    'dashboard.studySession': 'جلسة دراسة',
    'dashboard.completedToday': 'تمت اليوم',
    'dashboard.thisWeek': 'هذا الأسبوع',
    'dashboard.pomodoroSessions': 'جلسات بومودورو',
    'dashboard.totalTime': 'الوقت الكلي',
    'dashboard.averageSession': 'متوسط الجلسة',
    'dashboard.studyStreak': 'سلسلة الدراسة',
    'dashboard.reviewCards': 'مراجعة البطاقات',
    'dashboard.createFlashcard': 'إنشاء بطاقة تعليمية',
    
    // Calendar
    'calendar.title': 'التقويم',
    'calendar.today': 'اليوم',
    'calendar.week': 'الأسبوع',
    'calendar.month': 'الشهر',
    'calendar.addEvent': 'إضافة حدث',
    'calendar.noEvents': 'لا توجد أحداث',
    'calendar.allDay': 'طوال اليوم',
    'calendar.createEvent': 'إنشاء حدث',
    'calendar.editEvent': 'تعديل حدث',
    'calendar.deleteEvent': 'حذف حدث',
    'calendar.eventDetails': 'تفاصيل الحدث',
    
    // Schedule
    'schedule.title': 'الجدول الزمني',
    'schedule.addEvent': 'إضافة حدث',
    'schedule.todaySchedule': 'جدول اليوم',
    'schedule.weeklyView': 'عرض أسبوعي',
    'schedule.monthlyView': 'عرض شهري',
    'schedule.noEvents': 'لا توجد أحداث مجدولة',
    'schedule.createNewEvent': 'إنشاء حدث جديد',
    'schedule.eventTitle': 'عنوان الحدث',
    'schedule.eventDescription': 'وصف الحدث',
    'schedule.eventDate': 'تاريخ الحدث',
    'schedule.eventTime': 'وقت الحدث',
    'schedule.saveEvent': 'حفظ الحدث',
    'schedule.editEvent': 'تعديل الحدث',
    'schedule.deleteEvent': 'حذف الحدث',
    'schedule.recurring': 'متكرر',
    'schedule.priority': 'الأولوية',
    'schedule.low': 'منخفضة',
    'schedule.medium': 'متوسطة',
    'schedule.high': 'عالية',
    
    // Flashcards
    'flashcards.title': 'البطاقات التعليمية',
    'flashcards.myDecks': 'مجموعاتي',
    'flashcards.createDeck': 'إنشاء مجموعة',
    'flashcards.study': 'دراسة',
    'flashcards.cards': 'بطاقات',
    'flashcards.noDecks': 'لا توجد مجموعات تم إنشاؤها',
    'flashcards.createFirst': 'أنشئ مجموعتك الأولى للبدء',
    'flashcards.studyMode': 'وضع الدراسة',
    'flashcards.showAnswer': 'عرض الإجابة',
    'flashcards.nextCard': 'البطاقة التالية',
    'flashcards.difficulty.again': 'مرة أخرى',
    'flashcards.difficulty.hard': 'صعب',
    'flashcards.difficulty.good': 'جيد',
    'flashcards.difficulty.easy': 'سهل',
    'flashcards.deckName': 'اسم المجموعة',
    'flashcards.deckDescription': 'وصف المجموعة',
    'flashcards.addCard': 'إضافة بطاقة',
    'flashcards.front': 'الوجه الأمامي',
    'flashcards.back': 'الوجه الخلفي',
    'flashcards.importDeck': 'استيراد مجموعة',
    'flashcards.exportDeck': 'تصدير مجموعة',
    'flashcards.statistics': 'الإحصائيات',
    'flashcards.masteredCards': 'البطاقات المتقنة',
    'flashcards.learningCards': 'البطاقات قيد التعلم',
    'flashcards.newCards': 'البطاقات الجديدة',
    'flashcards.reviewCards': 'البطاقات للمراجعة',
    
    // Revision
    'revision.title': 'المراجعة',
    'revision.today': 'اليوم',
    'revision.upcoming': 'القادمة',
    'revision.overdue': 'متأخرة',
    'revision.completed': 'مكتملة',
    'revision.addItem': 'إضافة عنصر',
    'revision.noItems': 'لا توجد عناصر مراجعة',
    'revision.markComplete': 'وضع علامة كمكتمل',
    'revision.postpone': 'تأجيل',
    'revision.edit': 'تعديل',
    'revision.delete': 'حذف',
    'revision.itemTitle': 'عنوان العنصر',
    'revision.itemDescription': 'وصف العنصر',
    'revision.dueDate': 'تاريخ الاستحقاق',
    'revision.priority': 'الأولوية',
    'revision.subject': 'المادة',
    'revision.createItem': 'إنشاء عنصر',
    'revision.editItem': 'تعديل عنصر',
    'revision.deleteItem': 'حذف عنصر',
    'revision.notes': 'ملاحظات',
    'revision.studyTime': 'وقت الدراسة',
    'revision.lastReviewed': 'آخر مراجعة',
    'revision.nextReview': 'المراجعة التالية',
    'revision.difficulty': 'الصعوبة',
    'revision.reviewInterval': 'فاصل المراجعة',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.appearance': 'المظهر',
    'settings.appearance.desc': 'تخصيص مظهر التطبيق',
    'settings.darkMode': 'الوضع المظلم',
    'settings.darkMode.desc': 'تفعيل السمة المظلمة',
    'settings.language': 'اللغة',
    'settings.language.placeholder': 'اختر اللغة',
    
    'settings.notifications': 'الإشعارات',
    'settings.notifications.desc': 'تكوين كيفية تلقي الإشعارات',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.pushNotifications.desc': 'تلقي الإشعارات في المتصفح',
    'settings.studyReminders': 'تذكيرات الدراسة',
    'settings.studyReminders.desc': 'تلقي تذكيرات لجلسات الدراسة',
    
    'settings.pomodoro': 'إعدادات البومودورو',
    'settings.pomodoro.desc': 'تكوين إعدادات مؤقت البومودورو',
    'settings.focusTime': 'وقت التركيز (دقيقة)',
    'settings.shortBreak': 'استراحة قصيرة (دقيقة)',
    'settings.longBreak': 'استراحة طويلة (دقيقة)',
    'settings.longBreakInterval': 'فترة الاستراحة الطويلة',
    'settings.autoStartBreaks': 'بدء الاستراحات تلقائياً',
    'settings.autoStartBreaks.desc': 'بدء الاستراحات تلقائياً بعد كل جلسة',
    
    'settings.resetData': 'إعادة تعيين البيانات',
    'settings.resetData.desc': 'إعادة تعيين أو تصدير بيانات التطبيق',
    'settings.deleteSchedule': 'حذف الجدول الزمني',
    'settings.deleteSchedule.btn': 'حذف الجدول الزمني',
    'settings.deleteAllData': 'حذف جميع البيانات',
    'settings.deleteAllData.btn': 'حذف كل شيء نهائياً',
    'settings.scheduleDeleted': 'تم حذف الجدول الزمني',
    'settings.scheduleDeleted.desc': 'تم حذف جميع أحداث الجدول الزمني',
    'settings.allDataDeleted': 'تم حذف جميع البيانات',
    'settings.allDataDeleted.desc': 'تم حذف جميع بيانات التطبيق نهائياً',
    
    'common.save': 'حفظ التغييرات',
    'common.cancel': 'إلغاء',
    'common.back': 'رجوع',
    
    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.personalInfo.desc': 'تكوين معلوماتك الشخصية',
    'profile.firstName': 'الاسم الأول',
    'profile.firstName.placeholder': 'اسمك الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.lastName.placeholder': 'اسم عائلتك',
    'profile.email': 'البريد الإلكتروني',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'السيرة الذاتية',
    'profile.bio.placeholder': 'أخبرنا عن نفسك...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.calendar': 'कैलेंडर',
    'nav.schedule': 'अनुसूची',
    'nav.revision': 'संशोधन',
    'nav.flashcards': 'फ्लैशकार्ड',
    'nav.settings': 'सेटिंग्स',
    'nav.profile': 'प्रोफ़ाइल',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.todayTasks': 'आज के कार्य',
    'dashboard.upcomingEvents': 'आगामी घटनाएँ',
    'dashboard.studyProgress': 'अध्ययन प्रगति',
    'dashboard.quickActions': 'त्वरित क्रियाएँ',
    'dashboard.addTask': 'कार्य जोड़ें',
    'dashboard.addEvent': 'घटना जोड़ें',
    'dashboard.startPomodoro': 'पोमोडोरो शुरू करें',
    'dashboard.noTasks': 'आज कोई कार्य नहीं',
    'dashboard.noEvents': 'कोई आगामी घटनाएँ नहीं',
    'dashboard.studySession': 'अध्ययन सत्र',
    'dashboard.completedToday': 'आज पूर्ण',
    'dashboard.thisWeek': 'इस सप्ताह',
    'dashboard.pomodoroSessions': 'पोमोडोरो सत्र',
    'dashboard.totalTime': 'कुल समय',
    'dashboard.averageSession': 'औसत सत्र',
    'dashboard.studyStreak': 'अध्ययन श्रृंखला',
    'dashboard.reviewCards': 'कार्ड समीक्षा',
    'dashboard.createFlashcard': 'फ्लैशकार्ड बनाएं',
    
    // Calendar
    'calendar.title': 'कैलेंडर',
    'calendar.today': 'आज',
    'calendar.week': 'सप्ताह',
    'calendar.month': 'महीना',
    'calendar.addEvent': 'घटना जोड़ें',
    'calendar.noEvents': 'कोई घटना नहीं',
    'calendar.allDay': 'पूरा दिन',
    'calendar.createEvent': 'घटना बनाएं',
    'calendar.editEvent': 'घटना संपादित करें',
    'calendar.deleteEvent': 'घटना हटाएं',
    'calendar.eventDetails': 'घटना विवरण',
    
    // Schedule
    'schedule.title': 'अनुसूची',
    'schedule.addEvent': 'घटना जोड़ें',
    'schedule.todaySchedule': 'आज की अनुसूची',
    'schedule.weeklyView': 'साप्ताहिक दृश्य',
    'schedule.monthlyView': 'मासिक दृश्य',
    'schedule.noEvents': 'कोई निर्धारित घटना नहीं',
    'schedule.createNewEvent': 'नई घटना बनाएं',
    'schedule.eventTitle': 'घटना शीर्षक',
    'schedule.eventDescription': 'घटना विवरण',
    'schedule.eventDate': 'घटना तिथि',
    'schedule.eventTime': 'घटना समय',
    'schedule.saveEvent': 'घटना सहेजें',
    'schedule.editEvent': 'घटना संपादित करें',
    'schedule.deleteEvent': 'घटना हटाएं',
    'schedule.recurring': 'पुनरावर्ती',
    'schedule.priority': 'प्राथमिकता',
    'schedule.low': 'कम',
    'schedule.medium': 'मध्यम',
    'schedule.high': 'उच्च',
    
    // Flashcards
    'flashcards.title': 'फ्लैशकार्ड',
    'flashcards.myDecks': 'मेरे डेक',
    'flashcards.createDeck': 'डेक बनाएं',
    'flashcards.study': 'अध्ययन करें',
    'flashcards.cards': 'कार्ड',
    'flashcards.noDecks': 'कोई डेक नहीं बनाया गया',
    'flashcards.createFirst': 'शुरू करने के लिए अपना पहला डेक बनाएं',
    'flashcards.studyMode': 'अध्ययन मोड',
    'flashcards.showAnswer': 'उत्तर दिखाएं',
    'flashcards.nextCard': 'अगला कार्ड',
    'flashcards.difficulty.again': 'फिर से',
    'flashcards.difficulty.hard': 'कठिन',
    'flashcards.difficulty.good': 'अच्छा',
    'flashcards.difficulty.easy': 'आसान',
    'flashcards.deckName': 'डेक का नाम',
    'flashcards.deckDescription': 'डेक विवरण',
    'flashcards.addCard': 'कार्ड जोड़ें',
    'flashcards.front': 'सामने',
    'flashcards.back': 'पीछे',
    'flashcards.importDeck': 'डेक आयात करें',
    'flashcards.exportDeck': 'डेक निर्यात करें',
    'flashcards.statistics': 'आंकड़े',
    'flashcards.masteredCards': 'मास्टर किए गए कार्ड',
    'flashcards.learningCards': 'सीखने वाले कार्ड',
    'flashcards.newCards': 'नए कार्ड',
    'flashcards.reviewCards': 'समीक्षा के लिए कार्ड',
    
    // Revision
    'revision.title': 'संशोधन',
    'revision.today': 'आज',
    'revision.upcoming': 'आगामी',
    'revision.overdue': 'मियाद समाप्त',
    'revision.completed': 'पूरा हुआ',
    'revision.addItem': 'आइटम जोड़ें',
    'revision.noItems': 'कोई संशोधन आइटम नहीं',
    'revision.markComplete': 'पूरा चिह्नित करें',
    'revision.postpone': 'स्थगित करें',
    'revision.edit': 'संपादित करें',
    'revision.delete': 'हटाएं',
    'revision.itemTitle': 'आइटम शीर्षक',
    'revision.itemDescription': 'आइटम विवरण',
    'revision.dueDate': 'नियत तारीख',
    'revision.priority': 'प्राथमिकता',
    'revision.subject': 'विषय',
    'revision.createItem': 'आइटम बनाएं',
    'revision.editItem': 'आइटम संपादित करें',
    'revision.deleteItem': 'आइटम हटाएं',
    'revision.notes': 'नोट्स',
    'revision.studyTime': 'अध्ययन समय',
    'revision.lastReviewed': 'अंतिम समीक्षा',
    'revision.nextReview': 'अगली समीक्षा',
    'revision.difficulty': 'कठिनाई',
    'revision.reviewInterval': 'समीक्षा अंतराल',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.appearance': 'दिखावट',
    'settings.appearance.desc': 'ऐप की दिखावट को कस्टमाइज़ करें',
    'settings.darkMode': 'डार्क मोड',
    'settings.darkMode.desc': 'डार्क थीम सक्षम करें',
    'settings.language': 'भाषा',
    'settings.language.placeholder': 'भाषा चुनें',
    
    'settings.notifications': 'सूचनाएं',
    'settings.notifications.desc': 'सूचनाएं कैसे प्राप्त करना चाहते हैं, इसे कॉन्फ़िगर करें',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.pushNotifications.desc': 'ब्राउज़र में सूचनाएं प्राप्त करें',
    'settings.studyReminders': 'अध्ययन अनुस्मारक',
    'settings.studyReminders.desc': 'अपने अध्ययन सत्रों के लिए अनुस्मारक प्राप्त करें',
    
    'settings.pomodoro': 'पोमोडोरो सेटिंग्स',
    'settings.pomodoro.desc': 'अपने पोमोडोरो टाइमर सेटिंग्स कॉन्फिगर करें',
    'settings.focusTime': 'फोकस समय (मिनट)',
    'settings.shortBreak': 'छोटी ब्रेक (मिनट)',
    'settings.longBreak': 'लंबी ब्रेक (मिनट)',
    'settings.longBreakInterval': 'लंबी ब्रेक अंतराल',
    'settings.autoStartBreaks': 'स्वचालित ब्रेक शुरू करें',
    'settings.autoStartBreaks.desc': 'प्रत्येक सत्र के बाद ब्रेक स्वचालित रूप से शुरू करें',
    
    'settings.resetData': 'डेटा रीसेट करें',
    'settings.resetData.desc': 'अपने ऐप डेटा को रीसेट या निर्यात करें',
    'settings.deleteSchedule': 'अनुसूची हटाएं',
    'settings.deleteSchedule.btn': 'अनुसूची हटाएं',
    'settings.deleteAllData': 'सभी डेटा हटाएं',
    'settings.deleteAllData.btn': 'सब कुछ स्थायी रूप से हटाएं',
    'settings.scheduleDeleted': 'अनुसूची हटा दी गई',
    'settings.scheduleDeleted.desc': 'सभी अनुसूची घटनाएं हटा दी गई हैं',
    'settings.allDataDeleted': 'सभी डेटा हटा दिया गया',
    'settings.allDataDeleted.desc': 'सभी ऐप डेटा स्थायी रूप से हटा दिया गया है',
    
    'common.save': 'परिवर्तन सहेजें',
    'common.cancel': 'रद्द करें',
    'common.back': 'वापस',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.personalInfo.desc': 'अपनी व्यक्तिगत जानकारी कॉन्फ़िगर करें',
    'profile.firstName': 'पहला नाम',
    'profile.firstName.placeholder': 'आपका पहला नाम',
    'profile.lastName': 'अंतिम नाम',
    'profile.lastName.placeholder': 'आपका अंतिम नाम',
    'profile.email': 'ईमेल',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'बायो',
    'profile.bio.placeholder': 'हमें अपने बारे में बताएं...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
  bn: {
    // Navigation
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.calendar': 'ক্যালেন্ডার',
    'nav.schedule': 'সময়সূচী',
    'nav.revision': 'পুনর্বিবেচনা',
    'nav.flashcards': 'ফ্ল্যাশকার্ড',
    'nav.settings': 'সেটিংস',
    'nav.profile': 'প্রোফাইল',
    
    // Dashboard
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.todayTasks': 'আজকের কাজ',
    'dashboard.upcomingEvents': 'আসন্ন ইভেন্ট',
    'dashboard.studyProgress': 'অধ্যয়নের অগ্রগতি',
    'dashboard.quickActions': 'দ্রুত ক্রিয়াকলাপ',
    'dashboard.addTask': 'কাজ যোগ করুন',
    'dashboard.addEvent': 'ইভেন্ট যোগ করুন',
    'dashboard.startPomodoro': 'পোমোডোরো শুরু করুন',
    'dashboard.noTasks': 'আজ কোনও কাজ নেই',
    'dashboard.noEvents': 'কোনও আসন্ন ইভেন্ট নেই',
    'dashboard.studySession': 'অধ্যয়ন সেশন',
    'dashboard.completedToday': 'আজ সম্পন্ন',
    'dashboard.thisWeek': 'এই সপ্তাহ',
    'dashboard.pomodoroSessions': 'পোমোডোরো সেশন',
    'dashboard.totalTime': 'মোট সময়',
    'dashboard.averageSession': 'গড় সেশন',
    'dashboard.studyStreak': 'অধ্যয়ন স্ট্রিক',
    'dashboard.reviewCards': 'কার্ড পর্যালোচনা',
    'dashboard.createFlashcard': 'ফ্ল্যাশকার্ড তৈরি করুন',
    
    // Calendar
    'calendar.title': 'ক্যালেন্ডার',
    'calendar.today': 'আজ',
    'calendar.week': 'সপ্তাহ',
    'calendar.month': 'মাস',
    'calendar.addEvent': 'ইভেন্ট যোগ করুন',
    'calendar.noEvents': 'কোনও ইভেন্ট নেই',
    'calendar.allDay': 'সারা দিন',
    'calendar.createEvent': 'ইভেন্ট তৈরি করুন',
    'calendar.editEvent': 'ইভেন্ট সম্পাদনা করুন',
    'calendar.deleteEvent': 'ইভেন্ট মুছুন',
    'calendar.eventDetails': 'ইভেন্টের বিবরণ',
    
    // Schedule
    'schedule.title': 'সময়সূচী',
    'schedule.addEvent': 'ইভেন্ট যোগ করুন',
    'schedule.todaySchedule': 'আজকের সময়সূচী',
    'schedule.weeklyView': 'সাপ্তাহিক দৃশ্য',
    'schedule.monthlyView': 'মাসিক দৃশ্য',
    'schedule.noEvents': 'কোনও নির্ধারিত ইভেন্ট নেই',
    'schedule.createNewEvent': 'নতুন ইভেন্ট তৈরি করুন',
    'schedule.eventTitle': 'ইভেন্ট শিরোনাম',
    'schedule.eventDescription': 'ইভেন্টের বিবরণ',
    'schedule.eventDate': 'ইভেন্টের তারিখ',
    'schedule.eventTime': 'ইভেন্টের সময়',
    'schedule.saveEvent': 'ইভেন্ট সংরক্ষণ করুন',
    'schedule.editEvent': 'ইভেন্ট সম্পাদনা করুন',
    'schedule.deleteEvent': 'ইভেন্ট মুছুন',
    'schedule.recurring': 'পুনরাবৃত্ত',
    'schedule.priority': 'অগ্রাধিকার',
    'schedule.low': 'কম',
    'schedule.medium': 'মাঝারি',
    'schedule.high': 'উচ্চ',
    
    // Flashcards
    'flashcards.title': 'ফ্ল্যাশকার্ড',
    'flashcards.myDecks': 'আমার ডেক',
    'flashcards.createDeck': 'ডেক তৈরি করুন',
    'flashcards.study': 'অধ্যয়ন করুন',
    'flashcards.cards': 'কার্ড',
    'flashcards.noDecks': 'কোনও ডেক তৈরি হয়নি',
    'flashcards.createFirst': 'শুরু করতে আপনার প্রথম ডেক তৈরি করুন',
    'flashcards.studyMode': 'অধ্যয়ন মোড',
    'flashcards.showAnswer': 'উত্তর দেখান',
    'flashcards.nextCard': 'পরবর্তী কার্ড',
    'flashcards.difficulty.again': 'আবার',
    'flashcards.difficulty.hard': 'কঠিন',
    'flashcards.difficulty.good': 'ভালো',
    'flashcards.difficulty.easy': 'সহজ',
    'flashcards.deckName': 'ডেকের নাম',
    'flashcards.deckDescription': 'ডেকের বিবরণ',
    'flashcards.addCard': 'কার্ড যোগ করুন',
    'flashcards.front': 'সামনে',
    'flashcards.back': 'পেছনে',
    'flashcards.importDeck': 'ডেক আমদানি করুন',
    'flashcards.exportDeck': 'ডেক রপ্তানি করুন',
    'flashcards.statistics': 'পরিসংখ্যান',
    'flashcards.masteredCards': 'মাস্টার্ড কার্ড',
    'flashcards.learningCards': 'শিখছে এমন কার্ড',
    'flashcards.newCards': 'নতুন কার্ড',
    'flashcards.reviewCards': 'পর্যালোচনার জন্য কার্ড',
    
    // Revision
    'revision.title': 'পুনর্বিবেচনা',
    'revision.today': 'আজ',
    'revision.upcoming': 'আসন্ন',
    'revision.overdue': 'বিলম্বিত',
    'revision.completed': 'সম্পন্ন',
    'revision.addItem': 'আইটেম যোগ করুন',
    'revision.noItems': 'কোনও পুনর্বিবেচনা আইটেম নেই',
    'revision.markComplete': 'সম্পন্ন হিসেবে চিহ্নিত করুন',
    'revision.postpone': 'স্থগিত করুন',
    'revision.edit': 'সম্পাদনা করুন',
    'revision.delete': 'মুছে ফেলুন',
    'revision.itemTitle': 'আইটেম শিরোনাম',
    'revision.itemDescription': 'আইটেম বিবরণ',
    'revision.dueDate': 'নির্ধারিত তারিখ',
    'revision.priority': 'অগ্রাধিকার',
    'revision.subject': 'বিষয়',
    'revision.createItem': 'আইটেম তৈরি করুন',
    'revision.editItem': 'আইটেম সম্পাদনা করুন',
    'revision.deleteItem': 'আইটেম মুছুন',
    'revision.notes': 'নোট',
    'revision.studyTime': 'অধ্যয়ন সময়',
    'revision.lastReviewed': 'সর্বশেষ পর্যালোচনা',
    'revision.nextReview': 'পরবর্তী পর্যালোচনা',
    'revision.difficulty': 'কঠিনতা',
    'revision.reviewInterval': 'পর্যালোচনা অন্তর',
    
    // Settings
    'settings.title': 'সেটিংস',
    'settings.appearance': 'দেখা',
    'settings.appearance.desc': 'অ্যাপের চেহারা কাস্টমাইজ করুন',
    'settings.darkMode': 'ডার্ক মোড',
    'settings.darkMode.desc': 'ডার্ক থিম সক্ষম করুন',
    'settings.language': 'ভাষা',
    'settings.language.placeholder': 'ভাষা নির্বাচন করুন',
    
    'settings.notifications': 'বিজ্ঞপ্তি',
    'settings.notifications.desc': 'আপনি কীভাবে বিজ্ঞপ্তি পেতে চান তা কনফিগার করুন',
    'settings.pushNotifications': 'পুশ বিজ্ঞপ্তি',
    'settings.pushNotifications.desc': 'ব্রাউজারে বিজ্ঞপ্তি গ্রহণ করুন',
    'settings.studyReminders': 'অধ্যয়ন অনুস্মারক',
    'settings.studyReminders.desc': 'আপনার অধ্যয়ন সেশনের জন্য অনুস্মারক গ্রহণ করুন',
    
    'settings.pomodoro': 'পোমোডোরো সেটিংস',
    'settings.pomodoro.desc': 'আপনার পোমোডোরো টাইমার সেটিংস কনফিগার করুন',
    'settings.focusTime': 'ফোকাস টাইম (মিনিট)',
    'settings.shortBreak': 'ছোট বিরতি (মিনিট)',
    'settings.longBreak': 'দীর্ঘ বিরতি (মিনিট)',
    'settings.longBreakInterval': 'দীর্ঘ বিরতির ব্যবধান',
    'settings.autoStartBreaks': 'স্বয়ংক্রিয়ভাবে বিরতি শুরু করুন',
    'settings.autoStartBreaks.desc': 'প্রতিটি সেশনের পর স্বয়ংক্রিয়ভাবে বিরতি শুরু করুন',
    
    'settings.resetData': 'ডেটা রিসেট করুন',
    'settings.resetData.desc': 'আপনার অ্যাপ ডেটা রিসেট বা এক্সপোর্ট করুন',
    'settings.deleteSchedule': 'সময়সূচী মুছুন',
    'settings.deleteSchedule.btn': 'সময়সূচী মুছুন',
    'settings.deleteAllData': 'সমস্ত ডেটা মুছে ফেলুন',
    'settings.deleteAllData.btn': 'সবকিছু স্থায়ীভাবে মুছে ফেলুন',
    'settings.scheduleDeleted': 'সময়সূচী মুছে ফেলা হয়েছে',
    'settings.scheduleDeleted.desc': 'সমস্ত সময়সূচী ইভেন্ট সরানো হয়েছে',
    'settings.allDataDeleted': 'সমস্ত ডেটা মুছে ফেলা হয়েছে',
    'settings.allDataDeleted.desc': 'সমস্ত অ্যাপ ডেটা স্থায়ীভাবে সরানো হয়েছে',
    
    'common.save': 'পরিবর্তন সংরক্ষণ করুন',
    'common.cancel': 'বাতিল',
    'common.back': 'ফিরে যান',
    
    // Profile
    'profile.title': 'প্রোফাইল',
    'profile.personalInfo': 'ব্যক্তিগত তথ্য',
    'profile.personalInfo.desc': 'আপনার ব্যক্তিগত তথ্য কনফিগার করুন',
    'profile.firstName': 'প্রথম নাম',
    'profile.firstName.placeholder': 'আপনার প্রথম নাম',
    'profile.lastName': 'শেষ নাম',
    'profile.lastName.placeholder': 'আপনার শেষ নাম',
    'profile.email': 'ইমেইল',
    'profile.email.placeholder': 'your@email.com',
    'profile.bio': 'বায়ো',
    'profile.bio.placeholder': 'আমাদের আপনার সম্পর্কে বলুন...',
    
    // Languages
    'language.ar': 'العربية',
    'language.bn': 'বাংলা',
    'language.en': 'English',
    'language.es': 'Español',
    'language.fr': 'Français',
    'language.hi': 'हिन्दी',
    'language.it': 'Italiano',
    'language.pt': 'Português',
    'language.ru': 'Русский',
    'language.zh': '中文',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setStoredLanguage] = useLocalStorage<Language>('language', 'pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const setLanguage = (newLanguage: Language) => {
    setStoredLanguage(newLanguage);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
