// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlnximvpztzpohoiljht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbnhpbXZwenR6cG9ob2lsamh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzcyNTgsImV4cCI6MjA2NTUxMzI1OH0.BjSwdW55AwwwoQlfEmtwfaMpucNfLk35DDkWlu5xr1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);