// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjtetznitmsetkcirnst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqdGV0em5pdG1zZXRrY2lybnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjA0NDEsImV4cCI6MjA2NTUzNjQ0MX0.H9UooqYZ5IfVYgg3qOUsSGIFGf3pkgYtLkfGcOXcpcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);